Annex60/Fluid/Actuators/Valves/Data/Generic.mo
Annex60/Fluid/Actuators/Valves/Data/Linear.mo
Annex60/Fluid/Actuators/Valves/Data/package.mo

This pull request will close #143

Added defaultComponentPrefixes for #143

---

Annex60/Fluid/BaseClasses/FlowModels/basicFlowFunction_dp.mo
Annex60/Fluid/BaseClasses/PartialResistance.mo

Corrected revision section for #148

---

Annex60/Fluid/Actuators/BaseClasses/PartialDamperExponential.mo

Added Evaluate=true for #154

---

Annex60/Fluid/Actuators/Valves/Examples/ThreeWayValves.mo
Annex60/Fluid/Actuators/Valves/Examples/TwoWayValvePressureIndependent.mo
Annex60/Fluid/Actuators/Valves/Examples/TwoWayValves.mo
Annex60/Fluid/Actuators/Valves/Examples/TwoWayValvesMotor.mo
Annex60/Fluid/Actuators/Valves/Examples/ValveParameterization.mo
Annex60/Fluid/Actuators/Valves/TwoWayPressureIndependent.mo

Fixed all comments.
I also added comments to instances in other examples in the same package.

Issue156 pressure ind valve

---

.gitignore

see http://stackoverflow.com/a/28499839/874701

also ignore dsmodelext11.c and dsmodelext22.obj

---

.gitignore

And another file created by Dymola, saw this one for the first time today

also ignore Dymola success file

---

Annex60/Controls/Continuous/Examples/SignalRanker.mo
Annex60/Fluid/Movers/Data/FlowControlled.mo
Annex60/Fluid/Movers/UsersGuide.mo

These three got lost during the merge conflict or were introduced in the master in the meantime.
@marcusfuchs could you also review this pull request and merge it? Thanks.

Issue166 html conflicts

---

Annex60/Fluid/Movers/UsersGuide.mo

Corrected html syntax

---

Annex60/Fluid/Movers/Data/Pumps/Wilo/CronolineIL80slash220dash4slash4.mo
Annex60/Fluid/Movers/Data/Pumps/Wilo/Stratos25slash1to4.mo
Annex60/Fluid/Movers/Data/Pumps/Wilo/Stratos25slash1to6.mo
Annex60/Fluid/Movers/Data/Pumps/Wilo/Stratos25slash1to8.mo
Annex60/Fluid/Movers/Data/Pumps/Wilo/Stratos30slash1to4.mo
Annex60/Fluid/Movers/Data/Pumps/Wilo/Stratos30slash1to8.mo
Annex60/Fluid/Movers/Data/Pumps/Wilo/Stratos32slash1to12.mo
Annex60/Fluid/Movers/Data/Pumps/Wilo/Stratos40slash1to12.mo
Annex60/Fluid/Movers/Data/Pumps/Wilo/Stratos40slash1to8.mo
Annex60/Fluid/Movers/Data/Pumps/Wilo/Stratos50slash1to12.mo
Annex60/Fluid/Movers/Data/Pumps/Wilo/Stratos80slash1to12.mo
Annex60/Fluid/Movers/Data/Pumps/Wilo/VeroLine80slash115dash2comma2slash2.mo
Annex60/Fluid/Movers/Data/Pumps/Wilo/package.mo
Annex60/Fluid/Movers/Data/Pumps/package.order
Annex60/Fluid/Movers/Validation/Power.mo
Annex60/Fluid/Movers/Validation/Pump_Nrpm_stratos.mo
Annex60/Fluid/Movers/Validation/Pump_stratos.mo

@Mathadon 
Can you please review this pull request, which would close #190 
All unit tests work.

Renamed Wilo data for #190

---

Annex60/Fluid/Interfaces/FourPortFlowResistanceParameters.mo
Annex60/Fluid/Interfaces/TwoPortFlowResistanceParameters.mo

Corrected documentation for #192

---

Annex60/Media/Air.mo

Bug fix for specificEntropy of Media.Air

---

Annex60/BoundaryConditions/WeatherData/ReaderTMY3.mo

double quotes for table attributes

---

Annex60/Fluid/Types.mo

Added extends for #208

---

Annex60/Fluid/BaseClasses/PartialThreeWayResistance.mo

Unit tests in ```Fluid``` folder run ok.
This is for #218

added allowFlowReversal-like option for PartialThreeWayResistance.mo

---

Annex60/Fluid/Actuators/Dampers/Examples/Damper.mo
Annex60/Fluid/Actuators/Dampers/Examples/VAVBoxExponential.mo
Annex60/Fluid/Actuators/Valves/Examples/ThreeWayValves.mo
Annex60/Fluid/Actuators/Valves/Examples/TwoWayValveTable.mo
Annex60/Fluid/Actuators/Valves/Examples/TwoWayValves.mo
Annex60/Fluid/Actuators/Valves/Examples/TwoWayValvesTable.mo
Annex60/Fluid/Actuators/Valves/Examples/ValveParameterization.mo
Annex60/Fluid/HeatExchangers/Validation/ConstantEffectiveness.mo
Annex60/Fluid/Interfaces/Examples/HeaterCooler_u.mo
Annex60/Fluid/Interfaces/Examples/Humidifier_u.mo
Annex60/Fluid/MassExchangers/Examples/ConstantEffectiveness.mo
Annex60/Fluid/Movers/FlowControlled_dp.mo
Annex60/Fluid/Movers/FlowControlled_m_flow.mo

Removed LinePattern.None for #220

---

Annex60/Fluid/MixingVolumes/MixingVolume.mo

Set final keyword for #230

---

Annex60/Fluid/Movers/FlowControlled_dp.mo

Changed sign of dp_actual for #226

---

Annex60/Fluid/HeatExchangers/HeaterCooler_u.mo
Annex60/Fluid/Interfaces/TwoPortHeatMassExchanger.mo

Closes #232
Also fixed a small typo in HeaterCooler_u

Issue232 heat mass exchanger docu

---

Annex60/BoundaryConditions/SkyTemperature/BlackBody.mo
Annex60/BoundaryConditions/SolarIrradiation/BaseClasses/DirectTiltedSurface.mo
Annex60/BoundaryConditions/SolarIrradiation/BaseClasses/SkyClearness.mo

Made a similar change in two other models.
This is for #235

converted algorithm section into equation section in BlackBody.mo

---

.gitignore

Added *.pyc to the gitignore file

---

Annex60/Fluid/HeatExchangers/Radiators/Examples/RadiatorEN442_2.mo

This closes #128 and replaces https://github.com/iea-annex60/modelica-annex60/pull/262

Issue128 nonliteral

---

Annex60/Types/Azimuth/package.mo
Annex60/Types/Tilt/package.mo

Use the word list to avoid ambiguities,

---

Annex60/Fluid/Sensors/TraceSubstances.mo
Annex60/Fluid/Sensors/TraceSubstancesTwoPort.mo

Reformulated assignment of s and assert for #268

---

Annex60/Fluid/Examples/AllowFlowReversalExample.mo

This merges Filips changes to a development branch to see if we can reduce the number of affected files which is 203 in the original pull request https://github.com/iea-annex60/modelica-annex60/pull/217

Merge to review and process #216

---

Annex60/Fluid/Sources/Outside_CpLowRise.mo

minor: one more paragraph that needs to be closed,

---

Annex60/Fluid/Actuators/Valves/Data/package.mo
Annex60/Fluid/Actuators/Valves/TwoWayEqualPercentage.mo
Annex60/Fluid/Actuators/Valves/TwoWayQuickOpening.mo
Annex60/Fluid/Actuators/Valves/TwoWayTable.mo

Updated valve comments for #287

---

Annex60/legal.html

Issue290 legal html

---

Annex60/Fluid/Movers/BaseClasses/Characteristics/efficiency.mo
Annex60/Fluid/Movers/BaseClasses/Characteristics/power.mo
Annex60/Fluid/Movers/BaseClasses/Characteristics/pressure.mo
Annex60/Fluid/Sensors/SpecificEnthalpy.mo
Annex60/Utilities/Math/Functions/smoothMin.mo
Annex60/package.mo

This PR fixes 6 errors in pedantic mode, all of them related to annotations.
There are still 8 errors and 8 warnings left.

towards pedantic code check #266

---

Annex60/BoundaryConditions/WeatherData/BaseClasses/getHeaderElementTMY3.mo
Annex60/BoundaryConditions/WeatherData/BaseClasses/getLatitudeTMY3.mo
Annex60/BoundaryConditions/WeatherData/BaseClasses/getLongitudeTMY3.mo
Annex60/BoundaryConditions/WeatherData/BaseClasses/getTimeZoneTMY3.mo
Annex60/BoundaryConditions/WeatherData/ReaderTMY3.mo

Replace __Dymola_loadSelector by loadSelector

---

Annex60/Fluid/Sources/Examples/TraceSubstancesFlowSource.mo
Annex60/Fluid/Sources/TraceSubstancesFlowSource.mo

this is a possible fix #331,
removing another error in pedantic mode

parameter value should be 0 if annotation connectorSizing is used,

---

Annex60/Fluid/Interfaces/FourPort.mo

this does not yet rename the model,
but it removes 1 out of 8 pedantic errors.

related to #299

---

README.md

Issue333 readme

---

Annex60/Experimental/Pipe/BaseClasses/HeatLossMod2.mo
Annex60/Experimental/Pipe/BaseClasses/package.order
Annex60/Experimental/Pipe/Examples/Comparisons/A60pipe.mo
Annex60/Experimental/Pipe/Examples/Comparisons/NoReverseCompHeatLossPipe.mo
Annex60/Experimental/Pipe/PipeHeatLossA60Mod_noAbs.mo
Annex60/Experimental/Pipe/package.order

New pipe model PipeHeatLossA60Mod2 using modified heat loss model heatLossMod2 + Modification example A60pipe (Issue #264)

Issue264 pipe

---

Annex60/BoundaryConditions/WeatherData/BaseClasses/Examples/GetAbsolutePath.mo

Get Absolute Path

---

Annex60/BoundaryConditions/SolarGeometry/BaseClasses/Declination.mo

Corrected typo for #346.

---

Annex60/BoundaryConditions/SolarGeometry/BaseClasses/Declination.mo
Annex60/BoundaryConditions/SolarGeometry/BaseClasses/SolarAzimuth.mo
Annex60/BoundaryConditions/SolarGeometry/IncidenceAngle.mo
Annex60/BoundaryConditions/SolarGeometry/ZenithAngle.mo
Annex60/BoundaryConditions/SolarIrradiation/DiffuseIsotropic.mo
Annex60/BoundaryConditions/SolarIrradiation/DiffusePerez.mo
Annex60/BoundaryConditions/SolarIrradiation/DirectTiltedSurface.mo
Annex60/BoundaryConditions/SolarIrradiation/package.mo
Annex60/BoundaryConditions/Types.mo
Annex60/BoundaryConditions/WeatherData/BaseClasses/CheckCeilingHeight.mo
Annex60/BoundaryConditions/WeatherData/BaseClasses/CheckPressure.mo
Annex60/BoundaryConditions/WeatherData/BaseClasses/CheckRadiation.mo
Annex60/BoundaryConditions/WeatherData/BaseClasses/ConvertRadiation.mo
Annex60/BoundaryConditions/WeatherData/BaseClasses/ConvertTime.mo
Annex60/BoundaryConditions/WeatherData/BaseClasses/EquationOfTime.mo
Annex60/BoundaryConditions/WeatherData/BaseClasses/LocalCivilTime.mo
Annex60/BoundaryConditions/WeatherData/BaseClasses/package.mo
Annex60/BoundaryConditions/WeatherData/package.mo

This will close #356.
This pull request fixes typos, updates documentation, adds parameters or constants to avoid repeated calculations, adds attributes to the ground reflectance and is reformatting various files.
All unit tests produce the same results.

Issue356 cleanup

---

Annex60/Fluid/Interfaces/PartialFourPort.mo
Annex60/Fluid/Interfaces/package.mo
Annex60/Fluid/Interfaces/package.order

Add PartialFourPort

---

Annex60/Fluid/Movers/BaseClasses/Characteristics/efficiency.mo
Annex60/Fluid/Movers/BaseClasses/Characteristics/efficiencyParameters.mo
Annex60/Fluid/Movers/BaseClasses/PowerInterface.mo

Modelica.SIunits.Efficiency is declared as 
```Modelica
type Efficiency = Real (
final quantity="Efficiency",
final unit="1",
min=0);
```

use Modelica.SIunits.Efficiency instead of Real

---

Annex60/Fluid/HeatExchangers/ConstantEffectiveness.mo
Annex60/Fluid/MassExchangers/ConstantEffectiveness.mo
Annex60/Fluid/Movers/BaseClasses/Characteristics/efficiencyParameters.mo
Annex60/Fluid/Movers/BaseClasses/FlowMachineInterface.mo
Annex60/Fluid/Movers/BaseClasses/PowerInterface.mo

This adds more changes to #369.
It also removes specifying the <code>min=0</code> as this is already done at the type declaration.
@thorade Can you please review and let me know whether I caught all occurrences. All unit tests work.

Issue370 efficiency

---

Annex60/Fluid/Interfaces/ConservationEquation.mo
Annex60/Fluid/Interfaces/StaticTwoPortConservationEquation.mo
Annex60/Fluid/MixingVolumes/BaseClasses/PartialMixingVolume.mo
Annex60/Fluid/MixingVolumes/MixingVolume.mo
Annex60/Fluid/Sensors/TraceSubstancesPpm.mo
Annex60/Fluid/Sensors/package.order

I created a first implementation for a changed mixing volume implementation. Let's see if we can agree on the basics before continuing with documentation and unit tests!

Issue372 co2

---

Annex60/Fluid/Actuators/BaseClasses/PartialThreeWayValve.mo
Annex60/Fluid/BaseClasses/PartialThreeWayResistance.mo

This will close #379.
All unit tests work.

Updated files for #379

---

Annex60/Fluid/Chillers/BaseClasses/Carnot.mo
Annex60/Fluid/Interfaces/FourPortHeatMassExchanger.mo
Annex60/Fluid/Interfaces/LumpedVolumeDeclarations.mo
Annex60/Fluid/Interfaces/PrescribedOutletStateParameters.mo
Annex60/Fluid/Interfaces/TwoPortHeatMassExchanger.mo

@Mathadon : I think c72c807 is all you need. Is this correct or do I miss something? If this is all, please go ahead and merge `issue390_substancedynamics_refactored` to the `master`.

Updated documentation for #390

---

Annex60/Fluid/Actuators/BaseClasses/PartialTwoWayValve.mo

Corrected documentation

---

Annex60/Fluid/MixingVolumes/Validation/BaseClasses/MoistureMixingConservation.mo
Annex60/Fluid/MixingVolumes/Validation/MoistureMixingConservationDynamicBalance.mo
Annex60/Fluid/MixingVolumes/Validation/MoistureMixingConservationSteadyState.mo

cleaned up layout of examples MoistureMixingConservation xxxx .mo

---

Annex60/Fluid/Examples/SimpleHouse.mo
Annex60/Fluid/Sensors/Examples/PPM.mo
Annex60/Utilities/Math/Examples/SmoothHeaviside.mo

Removed __Dymola_experimentSetupOutput(events=false) for #437

---

Annex60/Fluid/BaseClasses/FlowModels/basicFlowFunction_dp.mo

Added work-around for #442

---

README.md

Not many manage to read HTML in source properly ;-)

Link to a rendered version of the legal page.

---

Annex60/BoundaryConditions/WeatherData/ReaderTMY3.mo

Updated url for weather data as the other is no longer valid

---

Annex60/BoundaryConditions/SolarIrradiation/BaseClasses/Examples/BrighteningCoefficient.mo
Annex60/BoundaryConditions/SolarIrradiation/BaseClasses/Examples/package.order
Annex60/BoundaryConditions/WeatherData/BaseClasses/Examples/CheckCeilingHeight.mo
Annex60/BoundaryConditions/WeatherData/BaseClasses/Examples/CheckPressure.mo
Annex60/BoundaryConditions/WeatherData/BaseClasses/Examples/CheckSkyCover.mo
Annex60/BoundaryConditions/WeatherData/BaseClasses/Examples/CheckTemperature.mo
Annex60/BoundaryConditions/WeatherData/BaseClasses/Examples/CheckWindDirection.mo
Annex60/BoundaryConditions/WeatherData/BaseClasses/Examples/CheckWindSpeed.mo
Annex60/BoundaryConditions/WeatherData/BaseClasses/Examples/ConvertRadiation.mo
Annex60/BoundaryConditions/WeatherData/BaseClasses/Examples/ConvertRelativeHumidity.mo
Annex60/BoundaryConditions/WeatherData/BaseClasses/Examples/GetHeaderElement.mo
Annex60/BoundaryConditions/WeatherData/BaseClasses/getAbsolutePath.mo
Annex60/BoundaryConditions/WeatherData/BaseClasses/getHeaderElementTMY3.mo
Annex60/BoundaryConditions/WeatherData/ReaderTMY3.mo
Annex60/Resources/Scripts/Dymola/BoundaryConditions/SolarIrradiation/BaseClasses/Examples/BrighteningCoefficient.mos

This closes #460.
Together with #461, this change allows to translate all models in `Annex60.BoundaryConditions` with JModelica.

Issue460 get absolute path

---

Annex60/BoundaryConditions/SolarIrradiation/DirectTiltedSurface.mo

This will close #461 
Together with #460, this change allows to translate all models in `Annex60.BoundaryConditions` with JModelica.

Removed duplicate instance weaBus. For #461

---

Annex60/Experimental/Benchmarks/AirFlow/Components/Staircase.mo
Annex60/Experimental/Benchmarks/AirFlow/Components/ZoneHallway.mo
Annex60/Fluid/Sources/BaseClasses/Outside.mo

Fixes models to prevent warnings in OM v1.9.6.
This closes #454

Issue454 air flow

---

.gitignore

named failure
content: one single line of text saying: Failed

ignore another temporary Dymola file

---

Annex60/Fluid/Examples/SimpleHouse.mo
Annex60/Utilities/Psychrometrics/Examples/TWetBul_TDryBulPhi.mo
Annex60/Utilities/Psychrometrics/Examples/TWetBul_TDryBulXi.mo

Updated graphical annotations

---

Annex60/Fluid/Movers/BaseClasses/PartialFlowMachine.mo

This closes #498 
I ran unit tests in Annex60.Fluid.Movers, which yielded the same results.

added custom implementation of extractor in PartialFlowMachine

---

Annex60/Fluid/Sensors/BaseClasses/PartialDynamicFlowSensor.mo

Improved documentation for tau. For #503

---

Annex60/BoundaryConditions/WeatherData/BaseClasses/getAbsolutePath.mo

Issue489 weather fmu

---

Annex60/Fluid/Movers/BaseClasses/Characteristics/pressure.mo
Annex60/Fluid/Movers/BaseClasses/FlowMachineInterface.mo

@mwetter 
the implementation that you suggested seems to work for my models
please verify if I took reasonable variables for `dpMax` and `V_flow_max`.
Unit tests in Movers package run fine for me.

implementation of pressure function that works for my models

---

Annex60/Fluid/Interfaces/PartialTwoPortTransport.mo
Annex60/package.mo

This will close #516 
All models work in Dymola 2017 FD01 beta2 with the pedantic model check.

Issue516 dymola2017 fd01

---

Annex60/Media/Specialized/Water/ConstantProperties_pT/package.mo
Annex60/Media/Specialized/Water/ConstantProperties_pT/package.order

This closes #518 .
The regression tests work and the library loads again in OpenModelica.

Issue518 water pt

---

Annex60/ThermalZones/ReducedOrder/RC/OneElement.mo

Issue522 init rc

---

Annex60/ThermalZones/ReducedOrder/EquivalentAirTemperature/BaseClasses/PartialVDI6007.mo
Annex60/ThermalZones/ReducedOrder/Examples/SimpleRoomFourElements.mo
Annex60/ThermalZones/ReducedOrder/Examples/SimpleRoomOneElement.mo
Annex60/ThermalZones/ReducedOrder/Examples/SimpleRoomThreeElements.mo
Annex60/ThermalZones/ReducedOrder/Examples/SimpleRoomTwoElements.mo
Annex60/ThermalZones/ReducedOrder/RC/FourElements.mo
Annex60/ThermalZones/ReducedOrder/RC/OneElement.mo
Annex60/ThermalZones/ReducedOrder/RC/ThreeElements.mo
Annex60/ThermalZones/ReducedOrder/RC/TwoElements.mo

Issue523 rom icons

---

Annex60/Controls/Continuous/Examples/LimPIDWithReset.mo

Added full path for #540

---

Annex60/Fluid/Interfaces/ConservationEquation.mo
Annex60/Media/Air.mo

Changed model names for #534

---

Annex60/Media/Specialized/Water/ConstantProperties_pT/package.mo

Corrected wrong hyperlink for #538

---

Annex60/Fluid/Movers/Validation/PumpCurveDerivatives.mo
Annex60/Types/package.mo

Removed non-required annotations

---

Annex60/Fluid/FixedResistances/Examples/SplitterFixedResistanceDpM.mo
Annex60/Fluid/FixedResistances/SplitterFixedResistanceDpM.mo
Annex60/ThermalZones/ReducedOrder/Validation/VDI6007/package.mo

Issue566 cleanup

---

Annex60/Fluid/MixingVolumes/Validation/MixingVolumeZeroFlow.mo

Removed assertion for #441

---

Annex60/Utilities/Math/IntegratorWithReset.mo

Corrected annotation, and made rendering conditional.

---

Annex60/Fluid/MixingVolumes/Validation/TraceSubstanceConservationDynamicBalance.mo

Removed C_nominal=zeros(Medium.nC) for #568

---

Annex60/Media/Air.mo

This closes #575. 
The unit tests work.

Set start value for #575

---

Annex60/Fluid/MixingVolumes/Validation/MixingVolume.mo

This closes #576.
The unit tests work.

Corrected wrong use of each keyword, and reformatted file

---

.gitignore

ignore dymosim

---

Annex60/Fluid/Movers/FlowControlled_dp.mo
Annex60/Fluid/Movers/FlowControlled_m_flow.mo

This closes #583 
All unit tests run.

Issue583 mover defaults

---

Annex60/Fluid/MixingVolumes/Validation/BaseClasses/MoistureMixingConservation.mo

Changed model to be partial

---

Annex60/Fluid/Actuators/BaseClasses/PartialTwoWayValve.mo

Relaxed assertion on phi for #592

---

Annex60/BoundaryConditions/WeatherData/BaseClasses/Examples/GetAbsolutePath.mo
Annex60/Resources/ReferenceResults/Dymola/Annex60_BoundaryConditions_WeatherData_BaseClasses_Examples_GetAbsolutePath.txt

Issue596 absolutepath

---

Annex60/Fluid/FixedResistances/FixedResistanceDpM.mo

removed icon labels from FixedResistanceDpM for #556

---

Annex60/ThermalZones/ReducedOrder/EquivalentAirTemperature/BaseClasses/PartialVDI6007.mo
Annex60/ThermalZones/ReducedOrder/Examples/SimpleRoomFourElements.mo
Annex60/ThermalZones/ReducedOrder/RC/OneElement.mo
Annex60/ThermalZones/ReducedOrder/SolarGain/BaseClasses/PartialCorrectionG.mo
Annex60/ThermalZones/ReducedOrder/Validation/VDI6007/TestCase1.mo
Annex60/ThermalZones/ReducedOrder/Validation/VDI6007/TestCase10.mo
Annex60/ThermalZones/ReducedOrder/Validation/VDI6007/TestCase11.mo
Annex60/ThermalZones/ReducedOrder/Validation/VDI6007/TestCase12.mo
Annex60/ThermalZones/ReducedOrder/Validation/VDI6007/TestCase2.mo
Annex60/ThermalZones/ReducedOrder/Validation/VDI6007/TestCase3.mo
Annex60/ThermalZones/ReducedOrder/Validation/VDI6007/TestCase4.mo
Annex60/ThermalZones/ReducedOrder/Validation/VDI6007/TestCase5.mo
Annex60/ThermalZones/ReducedOrder/Validation/VDI6007/TestCase6.mo
Annex60/ThermalZones/ReducedOrder/Validation/VDI6007/TestCase7.mo
Annex60/ThermalZones/ReducedOrder/Validation/VDI6007/TestCase8.mo
Annex60/ThermalZones/ReducedOrder/Validation/VDI6007/TestCase9.mo

Adds `experiment` annotation to validation examples
This closes #610

Adds `each` definitions to various models

---

Annex60/ThermalZones/ReducedOrder/SolarGain/CorrectionGDoublePane.mo

Changes description of CorrectionGDoublePane model

---

Annex60/ThermalZones/ReducedOrder/RC/OneElement.mo

introduces each final for fluid port definition in OneElement

---

Annex60/Fluid/HeatExchangers/ActiveBeams/BaseClasses/DerivativesCubicSpline.mo

This will close #629 and is needed to avoid an error in the JModelica testing due to a wrong annotation.

Removed wrong annotation and made icon smooth

---

Annex60/Utilities/Time/CalendarTime.mo

add .0 to enforce reals

---

Annex60/Controls/Continuous/package.mo
Annex60/Controls/Discrete/package.mo
Annex60/Controls/SetPoints/package.mo
Annex60/Controls/package.mo
Annex60/Fluid/Actuators/Dampers/package.mo
Annex60/Fluid/Actuators/Motors/package.mo
Annex60/Fluid/Actuators/Valves/package.mo
Annex60/Fluid/Actuators/package.mo
Annex60/Fluid/Chillers/package.mo
Annex60/Fluid/Delays/package.mo
Annex60/Fluid/FixedResistances/package.mo
Annex60/Fluid/HeatExchangers/Validation/ConstantEffectiveness.mo
Annex60/Fluid/HeatPumps/Carnot_TCon.mo
Annex60/Fluid/HeatPumps/Carnot_y.mo
Annex60/Fluid/HeatPumps/Examples/Carnot_TCon.mo
Annex60/Fluid/HeatPumps/Validation/Carnot_TCon_LowTemperature.mo
Annex60/Fluid/HeatPumps/Validation/Carnot_TCon_reverseFlow.mo
Annex60/Fluid/HeatPumps/Validation/package.mo
Annex60/Fluid/HeatPumps/package.mo
Annex60/Fluid/Movers/package.mo
Annex60/Utilities/Diagnostics/package.mo

This closes #678 
Adds documentation and does various file cleanups.
The regression tests work without error.

Issue678 cleanup

---

Annex60/Resources/Scripts/Dymola/Fluid/FixedResistances/Validation/PressureDropsSeries.mos

Corrected script for #680

---

.travis.yml
IBPSA/Resources/Scripts/travis/Makefile
IBPSA/Resources/Scripts/travis/usr/local/bin/dymola

Issue684 ci

---

IBPSA/Fluid/Sensors/BaseClasses/PartialAbsoluteSensor.mo

for #687
I ran unit tests in `Fluid.Sensors` which yielded 1 false negative.

set m_flow(max=0) in PartialAbsoluteSensor

---

IBPSA/Fluid/Types.mo

Added ConstantTemperaturePhaseChange for #694

---

IBPSA/BoundaryConditions/WeatherData/BaseClasses/Examples/ConvertTime.mo
IBPSA/Resources/Scripts/Dymola/BoundaryConditions/WeatherData/BaseClasses/Examples/ConvertTime.mos

This fixes #705. Unit tests results haven't changed.

Fix literal in mos and mo files

---

IBPSA/Fluid/MixingVolumes/Validation/BaseClasses/TraceSubstanceConservation.mo

now using correct base branch
this closes #708

removed experiment annotation for #708 in TraceSubstanceConservation.mo

---

IBPSA/Fluid/Movers/Validation/PumpCurveDerivatives.mo

This closes #709 and does not change any of the unit tests results.

Added experiment annotation

---

IBPSA/Fluid/HeatPumps/package.mo
IBPSA/Fluid/Movers/Validation/PumpCurveDerivatives.mo

Issue715 cleanup

---

IBPSA/Fluid/Sources/Boundary_pT.mo
IBPSA/Fluid/Sources/Boundary_ph.mo
IBPSA/Fluid/Sources/FixedBoundary.mo
IBPSA/Fluid/Sources/MassFlowSource_T.mo
IBPSA/Fluid/Sources/MassFlowSource_h.mo

moved checkBoundary to initial equation section

---

IBPSA/Fluid/BaseClasses/FlowModels/basicFlowFunction_dp_der.mo

changed implementation of basicFlowFunction_dp_der for #723

---

IBPSA/Resources/Scripts/JModelica/README.md
IBPSA/Resources/Scripts/JModelica/buildingspy_to_csv.py
IBPSA/Resources/Scripts/JModelica/getReferenceResults.py

Added files for JModelica verification

---

IBPSA/Fluid/Interfaces/StaticTwoPortConservationEquation.mo

Revised test for energy conservation at small mass flow rates.

---

IBPSA/Fluid/Interfaces/StaticTwoPortConservationEquation.mo

This closes #741 if all tests pass.

Reimplemented check for energy conservation

---

IBPSA/Resources/Scripts/Dymola/Utilities/Math/Functions/Examples/QuinticHermite.mos

added tolerance for #755

---

IBPSA/Utilities/Time/CalendarTime.mo

Fix calendar time

---

IBPSA/Utilities/Psychrometrics/TWetBul_TDryBulXi.mo

changed computation of iWat in TWetBul_TDryBulXi for #759

---

IBPSA/Fluid/MixingVolumes/BaseClasses/PartialMixingVolume.mo
IBPSA/Resources/Scripts/JModelica/getReferenceResults.py
IBPSA/ThermalZones/ReducedOrder/RC/BaseClasses/splitFacVal.mo
IBPSA/ThermalZones/ReducedOrder/RC/FourElements.mo
IBPSA/ThermalZones/ReducedOrder/RC/OneElement.mo
IBPSA/ThermalZones/ReducedOrder/RC/ThreeElements.mo
IBPSA/ThermalZones/ReducedOrder/RC/TwoElements.mo

Tbeu fix typos

---

bin/runUnitTests.py

This closes #774.@mathadon: Could you please review and merge? It is the same file as on the Buildings branch.

Updated run unittests

---

IBPSA/Fluid/Chillers/Validation/Carnot_TEva_2ndLaw.mo

Corrected typo

---

IBPSA/Fluid/Sources/BaseClasses/Outside.mo

Fixed the incorrect substance X.

Issue787 fix substance x

---

IBPSA/Fluid/Examples/Performance/PressureDrop/ParallelDp.mo
IBPSA/Fluid/Examples/Performance/PressureDrop/ParallelDpOptimised.mo
IBPSA/Fluid/Examples/Performance/PressureDrop/ParallelFlow.mo
IBPSA/Fluid/Examples/Performance/PressureDrop/ParallelFlowOptimised.mo
IBPSA/Fluid/Examples/Performance/PressureDrop/SeriesDp.mo
IBPSA/Fluid/Examples/Performance/PressureDrop/SeriesDpOptimised.mo
IBPSA/Fluid/Examples/Performance/PressureDrop/SeriesFlow.mo
IBPSA/Fluid/Examples/Performance/PressureDrop/SeriesFlowOptimised.mo
IBPSA/Fluid/Examples/Performance/PressureDrop/SeriesParallelDp.mo
IBPSA/Fluid/Examples/Performance/PressureDrop/SeriesParallelDpOptimised.mo
IBPSA/Fluid/Examples/Performance/PressureDrop/SeriesParallelFlow.mo
IBPSA/Fluid/Examples/Performance/PressureDrop/SeriesParallelFlowOptimised.mo

@marcusfuchs or @mlauster Could you please review this? The change is minor. I am just adding `experiment` annotation to models which is a requirement for the JModelica verification. This doesn't change results but should be merged to the master asap otherwise models on the master will fail once the changes I made in https://github.com/ibpsa/modelica-ibpsa/pull/797 are merged (@mwetter).
@Mathadon I fixed your models.
This closes #798.

Added experiment annotation to models

---

IBPSA/Fluid/Movers/BaseClasses/PartialFlowMachine.mo
IBPSA/Fluid/Movers/FlowControlled_dp.mo
IBPSA/Fluid/Movers/FlowControlled_m_flow.mo
IBPSA/Fluid/Movers/SpeedControlled_Nrpm.mo
IBPSA/Fluid/Movers/SpeedControlled_y.mo
IBPSA/Fluid/Movers/Validation/BaseClasses/ControlledFlowMachine.mo
IBPSA/Fluid/Movers/Validation/PowerSimplified.mo

This closes #802.
Changes were only made to the annotation to move connectors and make sure all are labelled correctly.

Issue802 mover icons

---

IBPSA/Fluid/FMI/Adaptors/Inlet.mo
IBPSA/Fluid/FMI/Adaptors/Outlet.mo
IBPSA/Fluid/FMI/ExportContainers/Examples/FMUs/Fan.mo
IBPSA/Fluid/FMI/ExportContainers/ReplaceableTwoPort.mo
IBPSA/Fluid/FMI/UsersGuide.mo
IBPSA/Fluid/HeatExchangers/ActiveBeams/BaseClasses/Examples/DerivateCubicSpline.mo
IBPSA/Fluid/Sensors/Velocity.mo

Issue817 broken links

---

IBPSA/Fluid/HeatExchangers/ActiveBeams/package.mo
IBPSA/Fluid/Humidifiers/package.mo

Added missing comments for #819

---

IBPSA/Fluid/FMI/Adaptors/HVAC.mo

Removed each for #822

---

IBPSA/Fluid/Sensors/PPM.mo
IBPSA/Fluid/Sensors/PPMTwoPort.mo

this replaces #832 
and should close #830

Issue830 each

---

IBPSA/BoundaryConditions/SolarGeometry/BaseClasses/SolarAzimuth.mo
IBPSA/BoundaryConditions/SolarGeometry/BaseClasses/WallSolarAzimuth.mo

Issue834 algorithm

---

IBPSA/Fluid/FMI/Conversion/Validation/InletToAirDryAir.mo
IBPSA/Fluid/FMI/Conversion/Validation/InletToAirDryAirCO2.mo
IBPSA/Fluid/FMI/Conversion/Validation/InletToAirMoistAirCO2.mo

replaceable medium

---

IBPSA/Fluid/FMI/Conversion/Validation/InletToAirDryAir.mo
IBPSA/Fluid/FMI/Conversion/Validation/InletToAirDryAirCO2.mo
IBPSA/Fluid/FMI/Conversion/Validation/InletToAirMoistAirCO2.mo

this closes #836 
and replaces PR #837

Issue836 replaceable

---

IBPSA/Controls/SetPoints/OccupancySchedule.mo

Removed print statement that was used during debugging only

---

IBPSA/BoundaryConditions/SkyTemperature/BlackBody.mo
IBPSA/Fluid/Humidifiers/Validation/SteamHumidifier_X.mo

Removed import statement for #852

---

IBPSA/BoundaryConditions/WeatherData/BaseClasses/getLatitudeTMY3.mo
IBPSA/BoundaryConditions/WeatherData/BaseClasses/getTimeSpanWeatherData.mo
IBPSA/BoundaryConditions/WeatherData/BaseClasses/package.order
IBPSA/BoundaryConditions/WeatherData/ReaderTMY3.mo

1. Added function to evaluate the time span of the weather data getTimeSpanWeatherData.mo.
2. Modified ReaderTMY3.mo to evaluate the time span and decide if the convert time block should be used or not.
3. Some minor modifications:
- changed longitude to latitude for error message in getLatitudeTMY3.mo
- added table name as parameter for ReaderTMY3.mo, in order not to have it hidden inside the model and address a more general approach to tables.
If review is passed, I can also update the documentation and the revision section of ReaderTMY3.mo

Modifications for #842

---

IBPSA/BoundaryConditions/WeatherData/BaseClasses/getTimeSpanWeatherData.mo
IBPSA/BoundaryConditions/WeatherData/ReaderTMY3.mo

1. Corrected html error.
2. Added start value for timeSpan in ReaderTMY3.mo and run function getTimeSpanWeatherData.mo using absolute file name.

First set of corrections for #842

---

IBPSA/BoundaryConditions/WeatherData/BaseClasses/getTimeSpanTMY3.mo
IBPSA/BoundaryConditions/WeatherData/BaseClasses/package.order
IBPSA/BoundaryConditions/WeatherData/ReaderTMY3.mo

Implementation of requested changes from #858

Implementation of requested changes from #858

---

IBPSA/BoundaryConditions/WeatherData/BaseClasses/getHeaderElementTMY3.mo
IBPSA/BoundaryConditions/WeatherData/BaseClasses/getLatitudeTMY3.mo
IBPSA/BoundaryConditions/WeatherData/BaseClasses/getLongitudeTMY3.mo
IBPSA/BoundaryConditions/WeatherData/BaseClasses/getTimeZoneTMY3.mo
IBPSA/BoundaryConditions/WeatherData/ReaderTMY3.mo

Updated revision section

---

IBPSA/BoundaryConditions/WeatherData/ReaderTMY3.mo
IBPSA/BoundaryConditions/WeatherData/Validation/DecemberToJanuary.mo

Deleted the start values for the timeSpan parameter and just added a filename to ReaderTMY3.mo

Example DecemberToJanuary.mo runs.

---

.gitignore

Gitignore diagnostics eventlog

---

IBPSA/Airflow/Multizone/EffectiveAirLeakageArea.mo
IBPSA/Fluid/Interfaces/PartialFourPortInterface.mo
IBPSA/Fluid/Interfaces/PartialTwoPortInterface.mo
IBPSA/Fluid/Interfaces/StaticTwoPortConservationEquation.mo
IBPSA/Fluid/Interfaces/StaticTwoPortHeatMassExchanger.mo
IBPSA/Fluid/MixingVolumes/Examples/MixingVolumeMoistAir.mo
IBPSA/Fluid/Movers/Data/Generic.mo
IBPSA/Media/Air.mo
IBPSA/Media/Specialized/Air/PerfectGas.mo

fixed incomplete bracket #879

---

IBPSA/Fluid/FixedResistances/PressureDrop.mo

now depends on from_dp
avoiding parameter divisions
see #884

modified implementation of PressureDrop for linearized=true

---

IBPSA/Fluid/Actuators/BaseClasses/ActuatorSignal.mo

propagated filter order of for #891

---

IBPSA/Fluid/FixedResistances/Junction.mo

removed final flowReversal=true in Junction for #898

---

.gitignore

ignore two more FMI related files

---

IBPSA/BoundaryConditions/SolarGeometry/BaseClasses/AltitudeAngle.mo
IBPSA/BoundaryConditions/SolarGeometry/BaseClasses/Declination.mo
IBPSA/BoundaryConditions/SolarGeometry/BaseClasses/Examples/WallSolarAzimuth.mo
IBPSA/BoundaryConditions/SolarGeometry/BaseClasses/IncidenceAngle.mo
IBPSA/BoundaryConditions/SolarGeometry/BaseClasses/SolarAzimuth.mo
IBPSA/BoundaryConditions/SolarGeometry/BaseClasses/SolarHourAngle.mo
IBPSA/BoundaryConditions/SolarGeometry/BaseClasses/WallSolarAzimuth.mo
IBPSA/BoundaryConditions/SolarGeometry/BaseClasses/ZenithAngle.mo
IBPSA/BoundaryConditions/SolarGeometry/IncidenceAngle.mo
IBPSA/BoundaryConditions/SolarGeometry/ZenithAngle.mo
IBPSA/BoundaryConditions/WeatherData/BaseClasses/CheckRelativeHumidity.mo
IBPSA/BoundaryConditions/WeatherData/BaseClasses/ConvertRelativeHumidity.mo

Corrected icons

---

IBPSA/Fluid/BaseClasses/PartialThreeWayResistance.mo

also added asserts that verify consistency of portFlowDirection values
see #902

added icon illustration of portFlowDirection

---

IBPSA/Fluid/Sources/BaseClasses/PartialSource.mo

Improved documentation for #930

---

IBPSA/package.mo

This closes #947 
We can discuss the release on tomorrow's call.
I suggest to release this version before merging the next backward incompatible changes. We can do another release afterwards when IDEAS requires a tagged version.

Issue947 release info 2 0 0

---

IBPSA/Fluid/FixedResistances/Validation/PlugFlowPipes/Data/BaseClasses/PipeDataULg.mo
IBPSA/Fluid/FixedResistances/Validation/PlugFlowPipes/Data/BaseClasses/package.mo
IBPSA/Fluid/FixedResistances/Validation/PlugFlowPipes/Data/PipeDataULg160104_2.mo
IBPSA/Fluid/FixedResistances/Validation/PlugFlowPipes/MSLAIT.mo
IBPSA/Fluid/FixedResistances/Validation/PlugFlowPipes/MSLAIT2Nodes.mo
IBPSA/Fluid/FixedResistances/Validation/PlugFlowPipes/PlugFlowAIT.mo
IBPSA/Fluid/MassExchangers/Validation/package.mo
IBPSA/Fluid/MassExchangers/package.mo
IBPSA/Fluid/MixingVolumes/Validation/CoupledVolumesWater.mo
IBPSA/Fluid/Storage/Examples/StratifiedUnloadAtMinimumTemperature.mo

Cleaned up code for #951

---

IBPSA/Controls/Continuous/OffTimer.mo
IBPSA/Fluid/Movers/BaseClasses/FlowMachineInterface.mo
IBPSA/Fluid/Movers/BaseClasses/PowerInterface.mo

Corrected obsolete icons for #955

---

IBPSA/Fluid/FixedResistances/LosslessPipe.mo

implemented allowFlowReversal for LossLessPipe

---

IBPSA/Fluid/Interfaces/StaticTwoPortConservationEquation.mo

This fixes in https://github.com/ibpsa/modelica-ibpsa/pull/964 empty spaces that should have been removed before merging it to the master.

Removed empty spaces at line endings

---

IBPSA/Airflow/Multizone/BaseClasses/DoorDiscretized.mo
IBPSA/Airflow/Multizone/BaseClasses/ErrorControl.mo
IBPSA/Airflow/Multizone/BaseClasses/TwoWayFlowElementBuoyancy.mo
IBPSA/Airflow/Multizone/DoorDiscretizedOpen.mo
IBPSA/Airflow/Multizone/DoorDiscretizedOperable.mo
IBPSA/Airflow/Multizone/MediumColumn.mo
IBPSA/Airflow/Multizone/MediumColumnDynamic.mo
IBPSA/Airflow/Multizone/Orifice.mo

This closes #972 
This only affects the revision notes, parameter information and grouping/tabbing of parameters.
No model equations have been changed.

Cleaned up model for #972

---

IBPSA/Utilities/IO/Examples/package.order

Deleted package.order

---

IBPSA/Media/Refrigerants/R410A/isentropicExponentVap_Tv.mo
IBPSA/Media/Refrigerants/R410A/package.mo
IBPSA/Media/Refrigerants/R410A/specificIsobaricHeatCapacityVap_Tv.mo
IBPSA/Media/Refrigerants/R410A/specificIsochoricHeatCapacityVap_Tv.mo

This closes #1005.
It removes leading `<U+FEFF>`

Removed non-ascii characters at the start of the file

---

IBPSA/Media/Refrigerants/R410A/isentropicExponentVap_Tv.mo
IBPSA/Media/Refrigerants/R410A/package.mo
IBPSA/Media/Refrigerants/R410A/specificIsobaricHeatCapacityVap_Tv.mo
IBPSA/Media/Refrigerants/R410A/specificIsochoricHeatCapacityVap_Tv.mo

do not use wide dash

---

IBPSA/Fluid/Interfaces/Examples/EightPortHeatMassExchanger.mo
IBPSA/Utilities/Math/Examples/Binomial.mo
IBPSA/Utilities/Math/Examples/Factorial.mo
IBPSA/Utilities/Math/Examples/FallingFactorial.mo

This removes import statements.

Removed import statement

---

IBPSA/Media/Refrigerants/R410A/isentropicExponentVap_Tv.mo
IBPSA/Media/Refrigerants/R410A/package.mo
IBPSA/Media/Refrigerants/R410A/specificIsobaricHeatCapacityVap_Tv.mo
IBPSA/Media/Refrigerants/R410A/specificIsochoricHeatCapacityVap_Tv.mo

this replaces #1012 and is related to #1005 
somehow I was never able to push directly to ibpsa branches
Merging IBPSA into BuildingSystem currently fails with utf8 errors, not sure what exactly is happening.

Issue1005 widedash

---

IBPSA/Utilities/IO/Files/BaseClasses/FileWriter.mo

clarified comment for #1010

---

IBPSA/Fluid/Sensors/BaseClasses/PartialAbsoluteSensor.mo
IBPSA/ThermalZones/ReducedOrder/Validation/VDI6007/BaseClasses/VerifyDifferenceThreePeriods.mo

Issue1014 dymola2019 fd01 beta1

---

IBPSA/Utilities/Math/Functions/BaseClasses/smoothTransition.mo

Changes if-statement to if-expression.

Issue1019 if smooth transition

---

IBPSA/Media/Antifreeze/PropyleneGlycolWater.mo

remove final keyword for T_max

---

IBPSA/Media/Antifreeze/package.mo

Extend from extends Modelica.Icons.Package
replaces #1031

Fix package icon

---

IBPSA/Resources/C-Sources/cryptographicsHash.c

Need to include stdlib.h for declaration of malloc
replaces #1030

Fix compilation

---

IBPSA/package.mo

@mwetter I already prepared some of the changes for the release. I'm not sure what else still has to happen, except for making a new tag?
this is for #996

updated release date and contributor list for #996

---

IBPSA/Utilities/IO/Files/BaseClasses/FileWriter.mo
IBPSA/Utilities/IO/Files/Examples/CSVWriter.mo

added parameter significantDigits in FileWriter

---

IBPSA/Media/Air.mo
IBPSA/Media/Antifreeze/PropyleneGlycolWater.mo
IBPSA/Media/Specialized/Air/PerfectGas.mo
IBPSA/Media/Water.mo

This closes #1045.
I suggest this change instead of https://github.com/ibpsa/modelica-ibpsa/pull/1046.
Please see #1045 for the rationale.

Issue1045 media assert separate min max

---

IBPSA/Media/Air.mo
IBPSA/Media/Antifreeze/PropyleneGlycolWater.mo
IBPSA/Media/Specialized/Air/PerfectGas.mo
IBPSA/Media/Water.mo

printing instance name when temperature assert triggers in media

---

IBPSA/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/BaseClasses/Functions/Validation/MultipoleThermalResistances_OneUTube.mo
IBPSA/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/BaseClasses/Functions/Validation/MultipoleThermalResistances_TwoUTube.mo
IBPSA/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/BaseClasses/Functions/internalResistancesOneUTube.mo
IBPSA/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/BaseClasses/Functions/internalResistancesTwoUTube.mo
IBPSA/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/BaseClasses/Functions/multipoleFluidTemperature.mo
IBPSA/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/BaseClasses/Functions/multipoleFmk.mo
IBPSA/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/BaseClasses/Functions/multipoleThermalResistances.mo
IBPSA/Fluid/Geothermal/Borefields/BaseClasses/HeatTransfer/LoadAggregation/aggregationWeightingFactors.mo

Issue1053 missing each geothermal

---

IBPSA/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/BaseClasses/Functions/multipoleThermalResistances.mo
IBPSA/Fluid/Geothermal/Borefields/BaseClasses/HeatTransfer/ThermalResponseFactors/Examples/GFunction_100boreholes.mo
IBPSA/Fluid/Geothermal/Borefields/BaseClasses/HeatTransfer/ThermalResponseFactors/Examples/GFunction_SmallScaleValidation.mo
IBPSA/Fluid/Geothermal/Borefields/BaseClasses/HeatTransfer/ThermalResponseFactors/Examples/TimeGeometric.mo

This closes #1060.
If I understand the error message correctly, all errors should be fixed. Is there a way to test it before merging?

Issue1060 Add each declaration to vector parameters

---

IBPSA/Fluid/Geothermal/Borefields/UsersGuide.mo

Corrected reference for #1064

---

IBPSA/Fluid/BaseClasses/FlowModels/basicFlowFunction_dp.mo
IBPSA/Fluid/BaseClasses/FlowModels/basicFlowFunction_dp_der.mo
IBPSA/Fluid/BaseClasses/FlowModels/basicFlowFunction_dp_der2.mo
IBPSA/Fluid/BaseClasses/FlowModels/basicFlowFunction_m_flow.mo
IBPSA/Fluid/BaseClasses/FlowModels/basicFlowFunction_m_flow_der.mo
IBPSA/Fluid/BaseClasses/FlowModels/basicFlowFunction_m_flow_der2.mo

Issue1070 inline

---

IBPSA/Fluid/Movers/BaseClasses/PartialFlowMachine.mo

added assert for m_flow_nominal in movers for #908

---

.travis.yml
IBPSA/Resources/Scripts/travis/bin/dymola

This closes #1074 
As the reference results remain the same, I will go ahead and merge this when all tests pass.

Issue1074 dymola2019 fd01

---

IBPSA/Utilities/Cryptographics/Validation/SHA1.mo

Reduced string length for #1081

---

IBPSA/Fluid/Movers/BaseClasses/PartialFlowMachine.mo

fix for jmodelica compiler warning for #1081

---

IBPSA/Fluid/Interfaces/PartialTwoPortVector.mo

This closes #1092 
This closes #1094

Issue1092 plugflow show t

---

IBPSA/Fluid/Interfaces/StaticTwoPortConservationEquation.mo

fixed typo

---

IBPSA/Utilities/Time/CalendarTime.mo

fix bug in CalendarTime.mo for non-zero offset.

---

IBPSA/Fluid/HeatExchangers/BaseClasses/PartialEffectiveness.mo

revised implementation of PartialEffectivess for #1102

---

IBPSA/BoundaryConditions/WeatherData/BaseClasses/ConvertTime.mo
IBPSA/BoundaryConditions/WeatherData/BaseClasses/Examples/CheckCeilingHeight.mo
IBPSA/BoundaryConditions/WeatherData/BaseClasses/Examples/CheckPressure.mo
IBPSA/BoundaryConditions/WeatherData/BaseClasses/Examples/CheckRadiation.mo
IBPSA/BoundaryConditions/WeatherData/BaseClasses/Examples/CheckRelativeHumidity.mo
IBPSA/BoundaryConditions/WeatherData/BaseClasses/Examples/CheckSkyCover.mo
IBPSA/BoundaryConditions/WeatherData/BaseClasses/Examples/CheckTemperature.mo
IBPSA/BoundaryConditions/WeatherData/BaseClasses/Examples/CheckWindDirection.mo
IBPSA/BoundaryConditions/WeatherData/BaseClasses/Examples/CheckWindSpeed.mo
IBPSA/BoundaryConditions/WeatherData/BaseClasses/Examples/ConvertRadiation.mo
IBPSA/BoundaryConditions/WeatherData/BaseClasses/Examples/ConvertRelativeHumidity.mo
IBPSA/BoundaryConditions/WeatherData/BaseClasses/Examples/ConvertTime.mo
IBPSA/BoundaryConditions/WeatherData/BaseClasses/getTimeSpanTMY3.mo
IBPSA/BoundaryConditions/WeatherData/ReaderTMY3.mo
IBPSA/BoundaryConditions/WeatherData/Validation/DecemberToJanuary.mo

Regarding #1096 
Removed average increment for weather file, and simplified IBPSA.BoundaryConditions.WeatherData.BaseClasses.ConvertTime
However I'm stuck with a dummy equation, so any help getting rid of it is greatly appreciated.

Issue842 multiyear, regarding #1096

---

IBPSA/Fluid/Geothermal/Borefields/BaseClasses/PartialBorefield.mo

added choicesallmatching

---

IBPSA/BoundaryConditions/WeatherData/BaseClasses/ConvertTime.mo
IBPSA/BoundaryConditions/WeatherData/BaseClasses/Examples/GetTimeSpanTMY3.mo
IBPSA/BoundaryConditions/WeatherData/BaseClasses/Examples/package.order
IBPSA/BoundaryConditions/WeatherData/ReaderTMY3.mo
IBPSA/Resources/ReferenceResults/Dymola/IBPSA_BoundaryConditions_WeatherData_BaseClasses_Examples_GetTimeSpanTMY3.txt
IBPSA/Resources/Scripts/Dymola/BoundaryConditions/WeatherData/BaseClasses/Examples/GetTimeSpanTMY3.mos

for #1108 
I added a test and reference results.
Extended documentation and error output.

Issue1108 get time span tmy3

---

IBPSA/Fluid/HeatExchangers/BaseClasses/HADryCoil.mo

Added instance name back again

---

IBPSA/Utilities/Math/Functions/fallingFactorial.mo

Changed limit for #1145

---

IBPSA/Fluid/package.mo

This is only a really small PR.
This closes #1150

add dp(0)/dt=0 #1150

---

.travis.yml
IBPSA/Resources/Scripts/travis/bin/jm_ipython.sh

Updated docker image for #1155

---

IBPSA/Fluid/Geothermal/Borefields/BaseClasses/PartialBorefield.mo

Added full class name for #1159

---

IBPSA/Resources/Scripts/travis/bin/jm_ipython.sh

Updated jm_ipython.sh

---

IBPSA/Fluid/Interfaces/PartialEightPortInterface.mo

Corrected medium for m4_flow

---

IBPSA/Fluid/HeatExchangers/Validation/DryCoilEffectivenessNTU.mo

This corrects the medium used in this example.

Corrected wrong Media that used Buildings instead of IBPSA

---

IBPSA/Fluid/Chillers/BaseClasses/Carnot.mo

Corrected wrong assignment and use of evaluate_etaPL

---

IBPSA/Fluid/Actuators/BaseClasses/ActuatorSignal.mo
IBPSA/Fluid/Actuators/BaseClasses/PartialThreeWayValve.mo
IBPSA/Fluid/Actuators/BaseClasses/PartialTwoWayValve.mo
IBPSA/Fluid/Actuators/BaseClasses/PartialTwoWayValveKv.mo
IBPSA/Fluid/Actuators/Valves/TwoWayPressureIndependent.mo
IBPSA/Fluid/BaseClasses/PartialResistance.mo
IBPSA/Fluid/Movers/BaseClasses/PartialFlowMachine.mo

Issue1225 graphical annotation

---

IBPSA/Fluid/Geothermal/Borefields/BaseClasses/HeatTransfer/ThermalResponseFactors/Validation/ShaGFunction.mo
IBPSA/Fluid/Geothermal/Borefields/BaseClasses/HeatTransfer/ThermalResponseFactors/shaGFunction.mo
IBPSA/Resources/ReferenceResults/Dymola/IBPSA_Fluid_Geothermal_Borefields_BaseClasses_HeatTransfer_ThermalResponseFactors_Validation_ShaGFunction.txt

Declared string as a constant for #1230

---

IBPSA/Fluid/MixingVolumes/BaseClasses/PartialMixingVolume.mo

closes #1228 
@mwetter can you review this?

improved flow reversal warning in PartialMixingVolume for #1228

---

IBPSA/Resources/Scripts/BuildingsPy/conf.json

Removed IBPSA.Airflow.Multizone.Examples.OneOpenDoor

---

IBPSA/Media/Antifreeze/BaseClasses/PropertyCoefficients.mo

Issue1239 Add in two lines parameter as keyword

---

IBPSA/Fluid/Actuators/BaseClasses/PartialThreeWayValve.mo
IBPSA/Fluid/Actuators/Valves/ThreeWayEqualPercentageLinear.mo
IBPSA/Fluid/Actuators/Valves/ThreeWayLinear.mo

This closes #1227.
@alexanderAKU: It would be nice if you could provide the table based three-way valve to the IBPSA library, assuming it is similar to `TwoWayTable`.

Issue1227 three way valve

---

IBPSA/Fluid/Actuators/BaseClasses/ActuatorSignal.mo

Set start attribute for #1252

---

IBPSA/Fluid/BaseClasses/IndexMassFraction.mo
IBPSA/Fluid/Sensors/TraceSubstances.mo
IBPSA/Fluid/Sources/TraceSubstancesFlowSource.mo

Issue1250 variable array index

---

.travis.yml
IBPSA/Resources/Scripts/travis/bin/dymola

Updated script for Dymola 2020x

---

IBPSA/Fluid/BaseClasses/FlowModels/basicFlowFunction_dp.mo
IBPSA/Fluid/BaseClasses/FlowModels/basicFlowFunction_m_flow.mo

Issue1240 smooth2

---

IBPSA/Fluid/MixingVolumes/Validation/BaseClasses/MixingVolumeReverseFlow.mo

Changed constraining clause for #1268

---

IBPSA/Utilities/IO/SignalExchange/Read.mo

This is for https://github.com/ibpsa/modelica-ibpsa/issues/1276.

Update signal exchange read block documentation

---

IBPSA/BoundaryConditions/WeatherData/BaseClasses/CheckBlackBodySkyTemperature.mo
IBPSA/BoundaryConditions/WeatherData/BaseClasses/CheckPressure.mo
IBPSA/BoundaryConditions/WeatherData/BaseClasses/CheckTemperature.mo

improved asserts that check weather data inputs

---

IBPSA/ThermalZones/ReducedOrder/RC/OneElement.mo

Issue1275 rom trace substances

---

IBPSA/Fluid/Actuators/Valves/ThreeWayTable.mo
IBPSA/Fluid/FixedResistances/Examples/FlowJunction.mo
IBPSA/Fluid/FixedResistances/Validation/FlowJunctionSteadyState.mo
IBPSA/Fluid/FixedResistances/Validation/FlowJunctionSteadyStateNoPressureDrop.mo
IBPSA/Fluid/HeatPumps/Compressors/BaseClasses/PartialCompressor.mo
IBPSA/Fluid/MixingVolumes/Validation/BaseClasses/MixingVolumeReverseFlow.mo
IBPSA/Fluid/Sources/TraceSubstancesFlowSource.mo
IBPSA/ThermalZones/ReducedOrder/Validation/VDI6007/BaseClasses/VerifyDifferenceThreePeriods.mo

Corrected broken hyperlinks

---

IBPSA/Media/Examples/SteamSaturatedProperties.mo
IBPSA/Media/Steam.mo

This addresses the comment in [Issue1206 media steam #1320](https://github.com/ibpsa/modelica-ibpsa/pull/1320) to add the `_sat` suffix to relevant steam media functions.
@mwetter, please let me know if you need anything else. Thanks!

Issue1206 media steam

---

IBPSA/Fluid/FMI/Adaptors/Examples/ThermalZoneHVACNoExhaust.mo
IBPSA/Fluid/FMI/ExportContainers/Examples/FMUs/ThermalZone.mo
IBPSA/Fluid/FMI/ExportContainers/Examples/FMUs/ThermalZones.mo
bin/verifyFiles.py

Added test for fontSize

---

IBPSA/Fluid/BaseClasses/PartialThreeWayResistance.mo

fix for #1327

---

IBPSA/Resources/C-Sources/fileWriterFree.c

This reverts commit 2708caca778e7949db0c66f027528dc8d76d3286.
closes #1332

Revert "Replaced sprintf to avoid potential buffer overflow"

---

IBPSA/Airflow/Multizone/BaseClasses/PowerLawResistance.mo
IBPSA/Fluid/Actuators/BaseClasses/PartialThreeWayValve.mo
IBPSA/Fluid/BaseClasses/PartialResistance.mo
IBPSA/Fluid/Chillers/BaseClasses/Carnot.mo
IBPSA/Fluid/FixedResistances/BaseClasses/PlugFlowCore.mo
IBPSA/Fluid/FixedResistances/Junction.mo
IBPSA/Fluid/FixedResistances/PlugFlowPipe.mo
IBPSA/Fluid/HeatExchangers/ActiveBeams/BaseClasses/Convector.mo
IBPSA/Fluid/HeatExchangers/ActiveBeams/Cooling.mo
IBPSA/Fluid/HeatExchangers/BaseClasses/PartialPrescribedOutlet.mo
IBPSA/Fluid/HeatExchangers/Radiators/RadiatorEN442_2.mo
IBPSA/Fluid/HeatPumps/BaseClasses/PartialWaterToWater.mo
IBPSA/Fluid/Interfaces/EightPortHeatMassExchanger.mo
IBPSA/Fluid/Interfaces/FourPortHeatMassExchanger.mo
IBPSA/Fluid/Interfaces/StaticFourPortHeatMassExchanger.mo
IBPSA/Fluid/Interfaces/StaticTwoPortHeatMassExchanger.mo
IBPSA/Fluid/Interfaces/TwoPortHeatMassExchanger.mo
IBPSA/Fluid/Movers/BaseClasses/FlowMachineInterface.mo
IBPSA/Fluid/Movers/BaseClasses/PowerInterface.mo
IBPSA/Fluid/Storage/BaseClasses/IndirectTankHeatExchanger.mo
bin/verifyFiles.py

Closes #1341.
This commit also updates the verification script to check for such declarations

Changed homotopyInitialization from parameter to constant

---

IBPSA/BoundaryConditions/BESTEST/IsotropicAndPerezDiffuseRadiation.mo
IBPSA/BoundaryConditions/BESTEST/UsersGuide.mo
IBPSA/BoundaryConditions/BESTEST/Validation/WD100.mo
IBPSA/BoundaryConditions/BESTEST/Validation/WD200.mo
IBPSA/BoundaryConditions/BESTEST/Validation/WD300.mo
IBPSA/BoundaryConditions/BESTEST/Validation/WD400.mo
IBPSA/BoundaryConditions/BESTEST/Validation/WD500.mo
IBPSA/BoundaryConditions/BESTEST/Validation/WD600.mo
IBPSA/BoundaryConditions/BESTEST/Validation/package.mo
IBPSA/Resources/Scripts/Dymola/BoundaryConditions/BESTEST/Validation/WD100.mos
IBPSA/Resources/Scripts/Dymola/BoundaryConditions/BESTEST/Validation/WD200.mos
IBPSA/Resources/Scripts/Dymola/BoundaryConditions/BESTEST/Validation/WD300.mos
IBPSA/Resources/Scripts/Dymola/BoundaryConditions/BESTEST/Validation/WD400.mos
IBPSA/Resources/Scripts/Dymola/BoundaryConditions/BESTEST/Validation/WD500.mos
IBPSA/Resources/Scripts/Dymola/BoundaryConditions/BESTEST/Validation/WD600.mos
IBPSA/Resources/src/BoundaryConditions/Validation/BESTEST/WeatherBESTEST.py

Addressed issues arised with VerifyFiles.py and RunUnitTests.py by correcting some html formatting and modifiyng the UnitTests examples

Issue1314 bestest weather

---

IBPSA/Fluid/FixedResistances/Validation/PlugFlowPipes/Data/BaseClasses/PipeDataULg.mo
IBPSA/Fluid/HeatExchangers/ActiveBeams/Examples/CoolingAndHeating.mo
IBPSA/Fluid/HeatExchangers/ActiveBeams/Examples/CoolingOnly.mo
IBPSA/Fluid/HeatExchangers/ActiveBeams/Examples/HeatingOnly.mo
IBPSA/Fluid/MixingVolumes/BaseClasses/PartialMixingVolume.mo
IBPSA/ThermalZones/ReducedOrder/RC/package.mo
IBPSA/Utilities/Psychrometrics/Functions/Examples/X_pSatpphi.mo
IBPSA/Utilities/Psychrometrics/TWetBul_TDryBulXi.mo

This commit applies 
```
find . -name '*.mo' | xargs sed -e 's/\&circ;/\&deg;/g' -i
```
Closes #1348

Corrected html

---

IBPSA/Fluid/HeatExchangers/BaseClasses/PartialEffectiveness.mo

This corrects only a minor typo.
I hope it was okay to bypass creating an issue.

Typo in PartialEffectiveness

---

IBPSA/Fluid/Actuators/Valves/TwoWayEqualPercentage.mo
IBPSA/Fluid/Actuators/Valves/TwoWayLinear.mo
IBPSA/Fluid/Actuators/Valves/TwoWayPolynomial.mo
IBPSA/Fluid/Actuators/Valves/TwoWayPressureIndependent.mo
IBPSA/Fluid/Actuators/Valves/TwoWayQuickOpening.mo
IBPSA/Fluid/Actuators/Valves/TwoWayTable.mo

Issue1376 valve leakage

---

IBPSA/Utilities/Psychrometrics/Functions/BaseClasses/der_saturationPressureLiquid.mo
IBPSA/Utilities/Psychrometrics/Functions/BaseClasses/der_sublimationPressureIce.mo

Corrected argument names

---

IBPSA/Fluid/Interfaces/StaticTwoPortConservationEquation.mo
IBPSA/Fluid/MixingVolumes/BaseClasses/PartialMixingVolume.mo

Set start values for hOut in class that instantiates the model

---

IBPSA/Media/Air.mo
IBPSA/Media/Water.mo

This closes #1401.
We could add the same refactoring to the other media, for now I did it for `Air` and `Water` as these are the ones we use most.

Issue1401 event indicators

---

IBPSA/Fluid/Actuators/BaseClasses/PartialDamperExponential.mo
IBPSA/Fluid/Examples/Performance/Example2.mo
IBPSA/Fluid/Interfaces/Examples/ReverseFlowHumidifier.mo
IBPSA/Fluid/Interfaces/Examples/ReverseFlowMassExchanger.mo
IBPSA/Fluid/MixingVolumes/Validation/TraceSubstanceConservationDynamicBalance.mo
IBPSA/Fluid/Sensors/BaseClasses/PartialAbsoluteSensor.mo

This closes #1419.
See also https://github.com/lbl-srg/BuildingsPy/issues/391

Corrected html for #1419

---

IBPSA/Fluid/HeatExchangers/BaseClasses/HACoilInside.mo
IBPSA/Fluid/HeatExchangers/BaseClasses/HADryCoil.mo

removed redundant icon annotation

---

IBPSA/Fluid/FixedResistances/BaseClasses/PlugFlowTransportDelay.mo

Issue1427: Negative tau in PlugFlowTransportDelay

---

IBPSA/Utilities/Psychrometrics/Functions/X_pW.mo

Issue1446 psychrometrics utility comment

---

IBPSA/Fluid/Sources/BaseClasses/PartialSource.mo

This closes #1462.
For https://github.com/lbl-srg/modelica-buildings/pull/2429

Corrected misplaced each

---

IBPSA/Fluid/Geothermal/Borefields/Examples/Borefields.mo
IBPSA/Fluid/Geothermal/Borefields/Validation/ConstantHeatInjection_100Boreholes.mo
IBPSA/Fluid/Geothermal/Borefields/Validation/Sandbox.mo

Added missing parameter keyword

---

IBPSA/Fluid/Geothermal/Borefields/BaseClasses/PartialBorefield.mo
IBPSA/Fluid/Storage/BaseClasses/IndirectTankHeatExchanger.mo

Corrected each placement for #1466

---

IBPSA/Fluid/Actuators/Dampers/Exponential.mo

Guarded against division by zero

---

IBPSA/Fluid/HeatPumps/Examples/ScrollWaterToWater_OneRoomRadiator.mo

Corrected assignment of design mass flow rate

---

IBPSA/Fluid/Humidifiers/Validation/SprayAirWasher_X.mo
IBPSA/Fluid/MixingVolumes/MixingVolumeMoistAir.mo
IBPSA/Fluid/MixingVolumes/Validation/BaseClasses/MixingVolumeReverseFlow.mo

Changed constrainedBy

---

IBPSA/Media/Air.mo

This adds a space that separates the number from the text.

Added missing space in message.

---

IBPSA/Fluid/HeatExchangers/BaseClasses/PartialPrescribedOutlet.mo
IBPSA/Fluid/Interfaces/PrescribedOutlet.mo

Removed duplicate declaration of m_flow_nominal

---

IBPSA/Resources/Data/BoundaryConditions/Validation/BESTEST/generateResults.py

Updated script so it works with Dymola 2022 which by default loads MSL 4.0.0

---

IBPSA/Fluid/HeatPumps/BaseClasses/PartialWaterToWater.mo
IBPSA/Fluid/HeatPumps/Compressors/ReciprocatingCompressor.mo
IBPSA/Fluid/HeatPumps/Compressors/ScrollCompressor.mo
IBPSA/Fluid/HeatPumps/ReciprocatingWaterToWater.mo
IBPSA/Fluid/HeatPumps/ScrollWaterToWater.mo
IBPSA/Resources/src/fluid/heatpumps/calibration/PythonModel/compressors.py
IBPSA/Resources/src/fluid/heatpumps/calibration/PythonModel/heatpumps.py
IBPSA/Resources/src/fluid/heatpumps/calibration/doc/build/html/compressors.html
IBPSA/Resources/src/fluid/heatpumps/calibration/doc/build/html/heatpumps.html

Corrected year for #1486

---

IBPSA/Airflow/Multizone/DoorOperable.mo

Removed dublicate variable declaration

---

IBPSA/Resources/src/fluid/heatpumps/calibration/PythonModel/refrigerants.py

This closes https://github.com/ibpsa/modelica-ibpsa/pull/1491
This closes #1490
@carlesRT : Thanks for the PR. We will handle it through this branch so it runs through the CI testing.
@MassimoCimmino : Can you please review and see if any other models need to be updated.

Issue1490 refrigerants bugfix

---

IBPSA/Resources/C-Sources/cryptographicsHash.c
IBPSA/Resources/C-Sources/getTimeSpan.c

Removed include statement for #1507

---

IBPSA/Fluid/Movers/UsersGuide.mo

Correct link to wrong model #1511

---

IBPSA/Fluid/Actuators/Dampers/PressureIndependent.mo

This closes #1513 
This change also reorders constant declarations.

Reformulated initial equation section for #1513

---

.github/workflows/formatting.yml
.github/workflows/jmodelica.yml
.travis.yml

See for example https://github.com/ibpsa/modelica-ibpsa/pull/1520/checks?check_run_id=3621818382

Removed setuptools as this causes failures in travis

---

IBPSA/Fluid/Movers/UsersGuide.mo

Corrected documentation for Mover Users' Guide #1527

---

IBPSA/Fluid/Geothermal/Borefields/BaseClasses/PartialBorefield.mo
IBPSA/Fluid/Storage/BaseClasses/IndirectTankHeatExchanger.mo

Corrected typo in link

---

IBPSA/Fluid/MixingVolumes/BaseClasses/MixingVolumeHeatMoisturePort.mo
IBPSA/Fluid/MixingVolumes/BaseClasses/MixingVolumeHeatPort.mo

Corrected typo in annotation

---

IBPSA/Resources/Data/BoundaryConditions/Validation/BESTEST/generateResults.py

This can be merged after https://github.com/lbl-srg/BuildingsPy/pull/437 is merged
This closes #1554

Avoided unloading MSL. For #1554

---

.travis.yml
IBPSA/Resources/Data/BoundaryConditions/Validation/BESTEST/generateResults.py

Updated BuildingsPy version

---

.github/workflows/formatting.yml
.travis.yml
IBPSA/Resources/Data/BoundaryConditions/Validation/BESTEST/generateResults.py

This is the version of BuildingsPy that likely is going to be released as 3.0.0
*Update*: Changed to BuildingsPy v3.0.0

Updated BuildingsPy to BuildingsPy@v3.0.0

---

.github/workflows/formatting.yml

See https://github.com/lbl-srg/BuildingsPy/security/dependabot/requirements.txt/PyYAML/open

Updated PyYAML to 5.4

---

IBPSA/Fluid/Interfaces/PartialEightPortInterface.mo
IBPSA/Fluid/Interfaces/PartialFourPortInterface.mo
IBPSA/Fluid/Interfaces/PartialTwoPortInterface.mo

Issue1578 port stream operator

---

IBPSA/Resources/C-Sources/getTimeSpan.c

Added compiler directives for #1596

---

IBPSA/Media/Specialized/Water/TemperatureDependentDensity.mo

Corrected unit error

---

IBPSA/legal.html
IBPSA/package.mo

This updates the copyright year to 2022

Updated copyright year

---

.travis.yml
IBPSA/Resources/Scripts/travis/dymola/dymola

This updates the Dymola image with a new license file.

Updated dymola image

---

.github/workflows/formatting.yml
.travis.yml

This updates BuildingsPy to the latest release

Update CI testing to BuildingsPy 4.0.0

---

IBPSA/Fluid/Storage/ExpansionVessel.mo
IBPSA/Resources/Scripts/Conversion/ConvertIBPSA_from_3.0_to_4.0.mos

Removed nonused parameter p in Fluid.Storage.ExpansionVessel

---

IBPSA/Fluid/Examples/ResistanceVolumeFlowReversal.mo
IBPSA/Fluid/Interfaces/PartialTwoPortTransport.mo
IBPSA/Fluid/Storage/Examples/StratifiedUnloadAtMinimumTemperature.mo

Issue1617 typo and misc

---

IBPSA/Fluid/HeatExchangers/HeaterCooler_u.mo

Closes #1642.
Add the missing unit "W" to the gain block.

Fix missing units #1642

---

IBPSA/package.mo

Updated version number to 4.0.0

---

IBPSA/ThermalZones/ReducedOrder/RC/OneElement.mo
IBPSA/ThermalZones/ReducedOrder/SolarGain/CorrectionGDoublePane.mo

Closes #1644 Making auxiliary parameters dimensionless.

Resolve unit inconsistency

---

IBPSA/Utilities/Math/Functions/regNonZeroPower.mo
IBPSA/Utilities/Math/RegNonZeroPower.mo

Improved documentation and implementation of regNonZeroPower

---

IBPSA/Fluid/Geothermal/Borefields/BaseClasses/HeatTransfer/ThermalResponseFactors/gFunction.mo

This initializes a variable that is accessed before initialization.
See https://github.com/OpenModelica/OpenModelica/issues/9707#issuecomment-1317631281

Initialized variable Done

---

.github/workflows/formatting.yml

This removes deprecated version (https://github.com/lbl-srg/modelica-buildings/actions/runs/3605039255)

Update set up of github actions

---

.github/workflows/formatting.yml
.travis.yml
IBPSA/Resources/Scripts/BuildingsPy/conf.yml

Increased time_out

---

IBPSA/Fluid/Movers/BaseClasses/Euler/approximation.mo
IBPSA/Fluid/Movers/BaseClasses/Euler/package.order
IBPSA/Fluid/Movers/Data/Generic.mo

@mwetter can this be merged? See https://github.com/ibpsa/modelica-ibpsa/pull/1646#issuecomment-1320920539

Issue1645 fan efficiency euler patch

---

IBPSA/Fluid/Storage/Examples/ExpansionVessel.mo

issue1679 expansion vessel old documentation

---

IBPSA/Utilities/Time/CalendarTime.mo

Refactored sampling to avoid rounding errors

---

IBPSA/Fluid/HeatExchangers/BaseClasses/PartialEffectivenessNTU.mo
IBPSA/Fluid/HeatExchangers/WetCoilEffectivenessNTU.mo

added noEvent()

---

IBPSA/Fluid/Actuators/Valves/ThreeWayEqualPercentageLinear.mo
IBPSA/Fluid/Actuators/Valves/ThreeWayLinear.mo
IBPSA/Fluid/Actuators/Valves/ThreeWayTable.mo
IBPSA/Fluid/HeatPumps/BaseClasses/PartialWaterToWater.mo
IBPSA/Media/Air.mo
IBPSA/Media/Steam.mo
IBPSA/Obsolete/Fluid/Sources/FixedBoundary.mo

Issue1699 misc fix

---

IBPSA/Fluid/Chillers/BaseClasses/Carnot.mo
IBPSA/Fluid/Chillers/Carnot_TEva.mo
IBPSA/Fluid/Chillers/Carnot_y.mo
IBPSA/Fluid/Chillers/Examples/Carnot_TEva.mo
IBPSA/Fluid/Chillers/Examples/Carnot_y.mo
IBPSA/Fluid/Chillers/Validation/Carnot_TEva_2ndLaw.mo
IBPSA/Fluid/Chillers/Validation/Carnot_TEva_reverseFlow.mo
IBPSA/Fluid/HeatPumps/Carnot_TCon.mo
IBPSA/Fluid/HeatPumps/Carnot_y.mo
IBPSA/Fluid/HeatPumps/Examples/Carnot_TCon.mo
IBPSA/Fluid/HeatPumps/Validation/Carnot_TCon_reverseFlow.mo

Changed etaCarnot_nominal binding to avoid a circular assignment

---

IBPSA/Fluid/Movers/UsersGuide.mo

Issue1702 mover paper doi

---

IBPSA/Fluid/Humidifiers/Humidifier_u.mo

Removed uses of non-existing parameter in annotation

---

IBPSA/Fluid/Movers/BaseClasses/PartialFlowMachine.mo

Issue1710 shorten mover warning messages

---

IBPSA/Fluid/Sources/Outside_CpLowRise.mo

Removed use of non-existent parameter in annotation

---

IBPSA/Fluid/HeatExchangers/BaseClasses/WetCoilWetRegime.mo

Set start value for NTU in WetCoilWetRegime

---

IBPSA/Fluid/HeatExchangers/BaseClasses/PartialEffectiveness.mo

issue 1732 capacity flow rates

---

.travis.yml

This updates the OpenModelica image.

Updated OpenModelica image

---

IBPSA/Resources/C-Sources/fileWriterFree.c
IBPSA/Resources/C-Sources/fileWriterStructure.c
IBPSA/Resources/C-Sources/getTimeSpan.c
IBPSA/Resources/C-Sources/jsonWriterInit.c

Added type cast for pointers

---

IBPSA/Media/Examples/BaseClasses/PartialProperties.mo

issue1742 self dependent binding

---

IBPSA/Fluid/Delays/DelayFirstOrder.mo

issue1745 minor grammar fix in documentation

---

.travis.yml

This updates the license file with a new date

Update Dymola license file

---

IBPSA/Fluid/Movers/UsersGuide.mo

This PR syncs further changes made in https://github.com/lbl-srg/modelica-buildings/pull/3376 related to #1737.

patch issue1737 show pressure curve

---

IBPSA/Resources/C-Sources/WeeklySchedule.c

This adds type cast for pointers. See #1751 and #1741
This closes #1751

Added typecast

---

IBPSA/Resources/src/fluid/heatpumps/calibration/doc/requirements.txt

This integrates the security alert from https://github.com/lbl-srg/modelica-buildings/pull/3407

Updated version of request to 2.31.0

---

IBPSA/Fluid/Geothermal/Borefields/BaseClasses/HeatTransfer/ThermalResponseFactors/finiteLineSource_Equivalent.mo
IBPSA/Fluid/Geothermal/Borefields/BaseClasses/HeatTransfer/ThermalResponseFactors/finiteLineSource_Integrand_Equivalent.mo
IBPSA/Obsolete/Fluid/Movers/Data/Pumps/Wilo/Stratos25slash1to4.mo
IBPSA/Obsolete/Fluid/Movers/Data/Pumps/Wilo/Stratos32slash1to12.mo

Issue 1760 correct broken links

---

IBPSA/Fluid/Geothermal/Aquifer/Examples/CoolingOffice.mo
IBPSA/Fluid/Geothermal/Aquifer/MultiWell.mo
IBPSA/Fluid/Geothermal/Aquifer/Validation/NumberWells.mo
IBPSA/Fluid/Geothermal/Aquifer/Validation/SimulationTest.mo

This adds a resistance for the vertical pipes.

Reconfigured flow resistance

---

IBPSA/package.mo

Added Kathryn Hinkelman to contributor list

---

.travis.yml

This updates to the master of BuildingsPy, which contains refactoring for the regression tests

Update .travis.yml with latest BuildingsPy

---

IBPSA/Fluid/Geothermal/Aquifer/Validation/NumberWells.mo

This is needed for merging the model to other libraries

Added full class path

---

IBPSA/Fluid/HeatExchangers/EvaporatorCondenser.mo

This closes #1810.
I will make a PR to Buildings master and Buildings maint 9 as well.

Issue1810 missing negative sign documentation

---

.travis.yml
IBPSA/Resources/Scripts/travis/dymola/dymola
IBPSA/Resources/Scripts/travis/omc/omc

This changes the repository for the docker images

Changed docker repository

---

IBPSA/Resources/C-Sources/getTimeSpan.c

Added missing header file declaration

---

IBPSA/Examples/Tutorial/SimpleHouse/SimpleHouse0.mo

The proper way to load files is with Modelica.Utilities.Files.loadResource

Replaced ModelicaServices

---

IBPSA/Fluid/Sensors/Examples/HeatMeter.mo
IBPSA/Fluid/Sensors/Examples/package.order
IBPSA/Fluid/Sensors/HeatMeter.mo
IBPSA/Fluid/Sensors/UsersGuide.mo
IBPSA/Fluid/Sensors/VolumeFlowRate.mo
IBPSA/Fluid/Sensors/package.order

Adds a HeatMeter as sensor corresponding to issue #1831 .

Add HeatMeter as sensor

---

IBPSA/Utilities/Time/CalendarTime.mo
IBPSA/Utilities/Time/Types/ZeroTime.mo

Issue1847 calendar time

---

IBPSA/Fluid/Geothermal/Aquifer/Data/Template.mo
IBPSA/Fluid/Geothermal/Aquifer/Examples/CoolingOffice.mo

Correct broken link in Acquifer package

---

IBPSA/Fluid/HeatExchangers/EvaporatorCondenser.mo
IBPSA/Fluid/Movers/Validation/BaseClasses/ControlledFlowMachine.mo

merged from Buildings

---

IBPSA/Fluid/FixedResistances/Validation/PlugFlowPipes/PlugFlowAIT.mo

Changed interval time specification

---

IBPSA/Fluid/HeatPumps/ModularReversible/Examples/LargeScaleWaterToWater_OneRoomRadiator.mo

This removes trailing white spaces

Removed whitespace

---

IBPSA/Resources/Scripts/Conversion/ConvertIBPSA_from_3.0_to_4.0.mos

This updates the conversion script for #1885

Add conversion for #1885

---

IBPSA/Fluid/SolarCollectors/Examples/FlatPlateWithTank.mo

Corrected instantiation of non-existent model

---

IBPSA/Electrical/Interfaces/Load.mo
IBPSA/Resources/Scripts/BuildingsPy/conf.yml

Changed default initialization of electrical load

---

.travis.yml

Updated Dymola to 2025x

---

README.md

This corrects a broken hyperlink

Update hyperlink in README.md

---

IBPSA/Airflow/Multizone/BaseClasses/DoorDiscretized.mo
IBPSA/Airflow/Multizone/BaseClasses/Examples/PowerLaw.mo
IBPSA/Airflow/Multizone/BaseClasses/Examples/PowerLawFixedM.mo
IBPSA/Airflow/Multizone/BaseClasses/Examples/package.mo
IBPSA/Airflow/Multizone/BaseClasses/TwoWayFlowElement.mo
IBPSA/Airflow/Multizone/BaseClasses/package.mo
IBPSA/Airflow/Multizone/BaseClasses/windPressureLowRise.mo
IBPSA/Airflow/Multizone/DoorDiscretizedOpen.mo
IBPSA/Airflow/Multizone/DoorDiscretizedOperable.mo
IBPSA/Airflow/Multizone/Examples/CO2TransportStep.mo
IBPSA/Airflow/Multizone/Examples/ChimneyShaftWithVolume.mo
IBPSA/Airflow/Multizone/Examples/ClosedDoors.mo
IBPSA/Airflow/Multizone/Examples/package.mo
IBPSA/Airflow/Multizone/UsersGuide.mo
IBPSA/Airflow/Multizone/Validation/package.mo
IBPSA/Airflow/package.mo
IBPSA/Electrical/AC/OnePhase/Conversion/ACACTransformer.mo
IBPSA/Electrical/AC/OnePhase/Loads/Inductive.mo
IBPSA/Electrical/AC/OnePhase/Loads/Resistive.mo
IBPSA/Electrical/DC/Loads/Conductor.mo
IBPSA/Electrical/Interfaces/ResistiveLoad.mo
IBPSA/Examples/package.mo
IBPSA/Fluid/Actuators/BaseClasses/PartialDamperExponential.mo
IBPSA/Fluid/Sources/Outside_CpLowRise.mo
IBPSA/ThermalZones/ISO13790/Validation/BESTEST/Cases6xx/Case600.mo
IBPSA/ThermalZones/ISO13790/Validation/BESTEST/Cases6xx/Case600FF.mo

Corrected links to Buildings with links to IBPSA

---

IBPSA/ThermalZones/ISO13790/Validation/BESTEST/Cases6xx/Case600.mo
IBPSA/ThermalZones/ISO13790/Validation/BESTEST/Cases6xx/Case600FF.mo
IBPSA/ThermalZones/ISO13790/Validation/BESTEST/UsersGuide.mo

replaced moveing average

---

IBPSA/Fluid/HeatPumps/ModularReversible/Examples/AirToWater2D_OneRoomRadiator.mo
IBPSA/Fluid/HeatPumps/ModularReversible/Examples/BaseClasses/PartialOneRoomRadiator.mo
IBPSA/Fluid/HeatPumps/ModularReversible/Examples/CarnotWithLosses_OneRoomRadiator.mo
IBPSA/Fluid/HeatPumps/ModularReversible/Examples/LargeScaleWaterToWater_OneRoomRadiator.mo
IBPSA/Fluid/HeatPumps/ModularReversible/Examples/Modular_OneRoomRadiator.mo
IBPSA/ThermalZones/ISO13790/Validation/BESTEST/Cases6xx/Case600.mo
IBPSA/ThermalZones/ISO13790/Validation/BESTEST/Cases6xx/Case600FF.mo

Issue1981 heat pump medium declaration

---

IBPSA/ThermalZones/ISO13790/Validation/BESTEST/Cases6xx/Case680FF.mo
IBPSA/ThermalZones/ISO13790/Validation/BESTEST/Cases9xx/Case980.mo

Add missing semi-colon in BESTEST validation models

---

IBPSA/Fluid/HeatPumps/ModularReversible/Data/TableData2D/EN14511/WAMAK_WaterToWater_220kW.mo

This closes #1989.
This PR only changes the documentation texts and will not lead to any results change.

issue 1989 fix WAMAK link

---

IBPSA/Fluid/Chillers/ModularReversible/Modular.mo
IBPSA/Fluid/HeatPumps/ModularReversible/BaseClasses/PartialReversibleRefrigerantMachine.mo
IBPSA/Fluid/HeatPumps/ModularReversible/Modular.mo

Remove hysteresis from PartialReversibleRefrigerantMachine

---

IBPSA/Electrical/BaseClasses/WindTurbine/PartialWindTurbine.mo

This closes #1996
@maltelenz: Thanks for reporting. This should correct the problem.

Changed numerical implementation for cut-off wind speed

---

IBPSA/Resources/Scripts/Conversion/ConvertIBPSA_from_3.0_to_4.0.mos

Updated conversion script to remove clear commands

---

.travis.yml

This updates the dymola image.

Update dymola image

---

IBPSA/Fluid/HeatPumps/ModularReversible/RefrigerantCycle/BaseClasses/PartialCarnot.mo

Update PartialCarnot.mo to set Evaluate=true for structural parameter

---

IBPSA/Fluid/Chillers/ModularReversible/Data/TableData2D/Generic.mo
IBPSA/Fluid/HeatPumps/ModularReversible/Controls/Safety/BaseClasses/PartialOperationalEnvelope.mo
IBPSA/Fluid/HeatPumps/ModularReversible/Controls/Safety/Data/Generic.mo
IBPSA/Fluid/HeatPumps/ModularReversible/Data/TableData2D/Generic.mo
IBPSA/Fluid/HeatPumps/ModularReversible/Data/TableData2D/GenericHeatPump.mo
IBPSA/Fluid/HeatPumps/ModularReversible/RefrigerantCycle/BaseClasses/PartialTableData2D.mo

Updated comment for modular heat pump and chiller parameters

---

IBPSA/BoundaryConditions/WeatherData/ReaderTMY3.mo

Closes #2017
@mwetter Please directly change the doc if you find the order or content of the new info misleading. I changed `Adding` to `Using` as adding to me always sounded like instructions for developers of the Library and not standard users which want to use different data. Especially because it states the files should be added to the resources of the library.

Update doc on how to get .mos data #2017

---

IBPSA/ThermalZones/ReducedOrder/Examples/SimpleRoomFourElementsTraceSubstance.mo

Added missing annotation 'Interval'
