ibpsa/modelica-ibpsa

- Annex60/Utilities/Math/Functions/inverseXRegularized.mo
- Annex60/Utilities/Math/Functions/smoothHeaviside.mo
- Annex60/Utilities/Math/Functions/smoothLimit.mo
- Annex60/Utilities/Math/Functions/smoothMax.mo
- Annex60/Utilities/Math/Functions/smoothMin.mo
Added ```smoothOrder = 1``` in inverseXRegularized, smoothHeaviside, smoothLimit, smoothMax, smoothMin
This is for issue #152
> issue 152: added smoothOrder = 1 

- Annex60/package.mo
This integrates the changes from UdK Berlin.
The wiki has already been updated.
> Updated the style guide for #180

- Annex60/Fluid/Actuators/Valves/Examples/TwoWayValvePressureIndependent.mo
- Annex60/Fluid/HeatExchangers/Examples/Heater_T.mo
- Annex60/Fluid/HeatExchangers/Examples/Heater_u.mo
- Annex60/Fluid/Interfaces/Examples/PrescribedOutletState.mo
- Annex60/Fluid/MixingVolumes/Examples/package.order
- Annex60/Fluid/Movers/BaseClasses/Characteristics/flowParameters.mo
- Annex60/Fluid/Movers/BaseClasses/FlowMachineInterface.mo
- Annex60/Fluid/Movers/BaseClasses/PowerInterface.mo
- Annex60/Fluid/Movers/FlowControlled_dp.mo
- Annex60/Fluid/Movers/SpeedControlled_Nrpm.mo
- Annex60/Fluid/Movers/SpeedControlled_y.mo
- Annex60/Utilities/Math/Examples/SmoothMin.mo
- Annex60/Utilities/Psychrometrics/Examples/Density_pTX.mo
- Annex60/Utilities/Psychrometrics/Examples/Phi_pTX.mo
This will close #185.
See the commit messages for a justification for each change.
The pump models have been tested again with OpenModelica and they still work (except for `Annex60.Fluid.Movers.Examples.SpeedControlled_y_pumpCurves` which also did not work prior to this change).
All unit tests produce the same results.
> Issue185 clean up

- Annex60/Fluid/Interfaces/PartialTwoPortTransport.mo
- Annex60/Fluid/Interfaces/PrescribedOutletState.mo
This closes #210 
It avoids non-needed calculations of the state at the port. See also https://github.com/lbl-srg/modelica-buildings/issues/388
All unit tests produce the same results.
> Issue210 state

- Annex60/Fluid/HeatExchangers/Radiators/RadiatorEN442_2.mo
instead of energyDynamics
this is for #214 
I reran all unit tests in the ```Fluid``` package. Only ```Heater_T``` gave different results, but since this does not use the radiator model I assume this is due to the different compiler.
> propagated vol.massDynamics in RadiatorEN442_2.mo to massDynamics 

- Annex60/Experimental/Benchmarks/AirFlow/Components/SimpleZone.mo
- Annex60/Experimental/Benchmarks/AirFlow/Components/Staircase.mo
- Annex60/Experimental/Benchmarks/AirFlow/Components/ZoneHallway.mo
- Annex60/Fluid/Examples/Performance/Example1v2.mo
- bin/runUnitTests.py
These changes are required for the models to translate in the pedantic Modelica mode.
The file `bin/runUnitTests.py` has also been changed to run the unit tests in the pedantic modelica mode. This requires the latest version of BuildingsPy from the master branch at https://github.com/lbl-srg/BuildingsPy
To use older versions of  BuildingsPy, the line
```
ut.pedanticModelica(True)
```
needs to be removed in `bin/runUnitTests.py`.
By default, BuildingsPy does not use pedantic modelica check as I don't expect that AixLib and IDEAS already work for that mode. Buildings does not yet work in pedantic check, but we will fix this.
> Issue266 pedantic

- bin/runUnitTests.py
This will close #383.
All changes are backwards compatible, and no change is needed to `BuildingsPy`.
> Issue383 run unit tests

- Annex60/Controls/SetPoints/Table.mo
This closes #508.
This change is not backwards compatible, but I doubt that any model accesses this protected parameter. The command for a conversion script is
```
convertElement("Annex60.Controls.SetPoints.Table",
"nCol",
"nRow");
```
> Changed protected final parameter nCol to nRow (non-backward compatible)

- Annex60/Airflow/Multizone/BaseClasses/TwoWayFlowElement.mo
- Annex60/Airflow/Multizone/MediumColumn.mo
- Annex60/Fluid/BaseClasses/PartialResistance.mo
- Annex60/Fluid/Interfaces/PartialFourPortInterface.mo
- Annex60/Fluid/Interfaces/PartialTwoPortInterface.mo
- Annex60/Fluid/Movers/BaseClasses/PartialFlowMachine.mo
This closes #552.
I also moved the computation of `dp` from the `equation` section to the variable declaration so that the model can be used for graphical modeling without having to mix graphical models with textual equations in the `equation` section, which is something we want to avoid per our style guide.
> Issue552 start values

- .gitignore
- Annex60/Controls/Continuous/LimPID.mo
> Dymola HTML export is saved to help/ by default,

- Annex60/Controls/Continuous/LimPID.mo
- Annex60/Fluid/FMI/UsersGuide.mo
- Annex60/Fluid/HeatExchangers/ActiveBeams/BaseClasses/Convector.mo
- Annex60/Fluid/Interfaces/Examples/FourPortHeatMassExchanger.mo
- Annex60/Utilities/Math/Examples/IntegratorWithReset.mo
- Annex60/Utilities/Math/IntegratorWithReset.mo
This closes some unclosed elements and fixes all HTML errors I was able to find.
I used Dymola 2017 FD01, File → Export → HTML → Printable package documentation 
and then loaded the resulting single HTML file into http://htmlhint.com/
HTML check using BuildingsPy and tidy also reports 0 errors.
> Html fixes

- Annex60/ThermalZones/ReducedOrder/Examples/package.order
- Annex60/ThermalZones/ReducedOrder/RC/BaseClasses/splitFacVal.mo
- Annex60/ThermalZones/ReducedOrder/Validation/VDI6007/package.order
make it a protected variable instead
this closes #652 
@mlauster All examples in the Validation.VDI6007 subpackage still simulate.
> remove keyword parameter,

- Annex60/Fluid/HeatExchangers/ActiveBeams/Data/Trox.mo
- Annex60/Fluid/HeatExchangers/ActiveBeams/Examples/CoolingAndHeating.mo
- Annex60/Fluid/HeatExchangers/ActiveBeams/Examples/CoolingOnly.mo
- Annex60/Fluid/HeatExchangers/ActiveBeams/Examples/HeatingOnly.mo
- Annex60/Fluid/HeatExchangers/ActiveBeams/UsersGuide.mo
- Annex60/Fluid/HeatExchangers/ActiveBeams/Validation/NumberOfBeams.mo
- Annex60/Resources/www/modelicaDoc.css
- Annex60/ThermalZones/ReducedOrder/EquivalentAirTemperature/VDI6007WithWindow.mo
- Annex60/ThermalZones/ReducedOrder/EquivalentAirTemperature/package.mo
- Annex60/ThermalZones/ReducedOrder/Examples/SimpleRoomFourElements.mo
- Annex60/ThermalZones/ReducedOrder/Examples/SimpleRoomOneElement.mo
- Annex60/ThermalZones/ReducedOrder/Examples/SimpleRoomThreeElements.mo
- Annex60/ThermalZones/ReducedOrder/Examples/SimpleRoomTwoElements.mo
- Annex60/ThermalZones/ReducedOrder/RC/BaseClasses/splitFacVal.mo
- Annex60/ThermalZones/ReducedOrder/RC/OneElement.mo
- Annex60/ThermalZones/ReducedOrder/RC/package.mo
- Annex60/ThermalZones/ReducedOrder/Validation/VDI6007/package.mo
- Annex60/Utilities/Math/Functions/average.mo
This fixes mostly typos in the documentation, but also a few variable names and one css class selector.
https://github.com/vlajos/misspell_fixer
> fix some typos

- Annex60/Fluid/FMI/Conversion/AirToOutlet.mo
- Annex60/Fluid/FMI/Conversion/InletToAir.mo
fixes an error in pedantic mode.
```
Advanced.PedanticModelica=true;
checkModel("Annex60.Fluid.FMI.Conversion");
```
> Placement.visible instead of Placement.transformation.visible

- Annex60/Fluid/FixedResistances/LosslessPipe.mo
RGB values should be in the range 0...255
OpenModelica was complaining about 256 being out of range
> RGB values should be in the range 0...255

- IBPSA/Fluid/Movers/BaseClasses/Characteristics/efficiency.mo
- IBPSA/Fluid/Movers/BaseClasses/PartialFlowMachine.mo
This is not 100% identical, as the MSL definition has a min value defined
```modelica
type Efficiency = Real (
final quantity="Efficiency",
final unit="1",
min=0);
```
If that was the reason why the MSL unit was not used one could also change the min value at instantiation:
```modelica
Modelica.SIunits.Efficiency etaHyd(min=-1) = eff.etaHyd "Hydraulic efficiency";
```
> Modelica.SIunits.Efficiency

- IBPSA/Fluid/Interfaces/ConservationEquation.mo
- IBPSA/Fluid/MixingVolumes/BaseClasses/Validation/MixingVolumeHeatPortAir.mo
- IBPSA/Resources/Scripts/Dymola/Fluid/MixingVolumes/BaseClasses/Validation/MixingVolumeHeatMoisturePort.mos
- IBPSA/Resources/Scripts/Dymola/Fluid/MixingVolumes/BaseClasses/Validation/MixingVolumeHeatPortAir.mos
- IBPSA/Resources/Scripts/Dymola/Fluid/MixingVolumes/BaseClasses/Validation/MixingVolumeHeatPortWater.mos
This closes #727
It also removed `displayUnit` in the mos script so that it can be plotted with Dymola 2017FD01.
> Issue727 start values

- IBPSA/Fluid/Actuators/Dampers/VAVBoxExponential.mo
- IBPSA/Fluid/BaseClasses/PartialThreeWayResistance.mo
- IBPSA/Fluid/Humidifiers/Humidifier_u.mo
- IBPSA/Fluid/Interfaces/ConservationEquation.mo
- IBPSA/Fluid/Interfaces/FourPortHeatMassExchanger.mo
- IBPSA/Fluid/MixingVolumes/BaseClasses/Validation/MixingVolumeHeatPortWater.mo
- IBPSA/Fluid/Movers/FlowControlled_dp.mo
- IBPSA/Fluid/Sensors/package.mo
- IBPSA/Media/Air.mo
This replaces https://github.com/ibpsa/modelica-ibpsa/pull/865
(as the pull request needs to be from the same repository for travis to work)
https://github.com/lbl-srg/BuildingsPy/issues/52
https://github.com/htacg/tidy-html5/issues/521
> close some unclosed list items

- .gitignore
[ci skip]
Does the CI skip command also work from PRs?
The files ignored are created when using the new debugging feature,
see https://github.com/UdK-VPT/BuildingSystems/issues/78#issuecomment-349312150
> ignore diagnostics and eventlog files

- IBPSA/Fluid/FixedResistances/Validation/PlugFlowPipes/PlugFlowULg.mo
- IBPSA/package.mo
This closes #988. (Note that the diff in github won't show the removed character.) On a console, the change is
```bash
$ git diff origin/master
diff --git a/IBPSA/Fluid/FixedResistances/Validation/PlugFlowPipes/PlugFlowULg.mo b/IBPSA/Fluid/FixedResistances/Validation/PlugFlowPipes/PlugFlowULg.mo
index b538a07a..a1d4d92c 100644
--- a/IBPSA/Fluid/FixedResistances/Validation/PlugFlowPipes/PlugFlowULg.mo
+++ b/IBPSA/Fluid/FixedResistances/Validation/PlugFlowPipes/PlugFlowULg.mo
@@ -1,4 +1,4 @@
-<U+FEFF>within IBPSA.Fluid.FixedResistances.Validation.PlugFlowPipes;
+within IBPSA.Fluid.FixedResistances.Validation.PlugFlowPipes;
model PlugFlowULg "Validation against data from Université de Liège"
extends Modelica.Icons.Example;
package Medium = IBPSA.Media.Water;
diff --git a/IBPSA/package.mo …
```
> Removed unicode character for #988

- IBPSA/Resources/C-Sources/fileWriterStructure.h
Fix MSVC compiler warning on different constness in arguments for strcpy or realloc
replaces #1032
> Fix warnings

- IBPSA/Utilities/IO/SignalExchange.mo
follows https://github.com/ibpsa/modelica-ibpsa/pull/1116 according to https://github.com/ibpsa/project1-boptest/issues/49
> issue1059_controlIONoSocket - Removed energy signals

- IBPSA/Resources/C-Sources/getTimeSpan.c
- IBPSA/package.mo
Reimplement `getline()` funciton. Successfully tested on Windows OS.
> Issue1136 reimplement getline

- IBPSA/ThermalZones/ReducedOrder/Validation/VDI6007/TestCase11.mo
Closes #1132. The validation for the VDI Thermal Zone model includes 12 test cases. Test case 11 is problematic because of its hard limits and assumptions. In the past, we skipped the first 60 seconds of each day in order to succeed with the validation. While this works on Linux, on Windows this is not enough to fulfil the test case reference. Now we skip the first 120 seconds, which at least makes the simulation succeed.
> "Fix" VDI test case 11 for Windows

- IBPSA/Fluid/Actuators/BaseClasses/PartialTwoWayValve.mo
- IBPSA/Fluid/Actuators/Valves/TwoWayEqualPercentage.mo
- IBPSA/Fluid/Actuators/Valves/TwoWayLinear.mo
- IBPSA/Fluid/Actuators/Valves/TwoWayPolynomial.mo
- IBPSA/Fluid/Actuators/Valves/TwoWayPressureIndependent.mo
- IBPSA/Fluid/Actuators/Valves/TwoWayQuickOpening.mo
- IBPSA/Fluid/Actuators/Valves/TwoWayTable.mo
removed assert that checks phi > -0.2
closes #1223
> added phi=max(y_actual,0) for all two way valves

- IBPSA/Fluid/Sources/BaseClasses/Outside.mo
- IBPSA/Fluid/Sources/MassFlowSource_WeatherData.mo
This closes #1248
This is simply a clean-up to avoid a warning as the connectors are already declared in the base class.
> Removed duplicate connector for #1248

- IBPSA/ThermalZones/ReducedOrder/RC/FourElements.mo
- IBPSA/ThermalZones/ReducedOrder/RC/ThreeElements.mo
This Closes #1258 
This changes `nExt` to `nFloor` and `nRoof` for `RFloor` and `CFloor` resp. `RRoof` and `CRoof`.
@LXUtue, please check if this fixes your problems.
@mwetter, please check if models still compile correctly, I unfortunately don't have any Dymola or JModelica installtion at hand.
Thanks!
> Incompatible sizes for variables ROM

- IBPSA/Airflow/Multizone/BaseClasses/PowerLawResistance.mo
- IBPSA/Airflow/Multizone/BaseClasses/TwoWayFlowElement.mo
- IBPSA/Airflow/Multizone/BaseClasses/ZonalFlow.mo
- IBPSA/Resources/Scripts/Dymola/ConvertIBPSA_from_3.0_to_4.0.mos
This closes #1362.
The entries for the conversion script are
```
convertModifiers("IBPSA.Airflow.Multizone.BaseClasses.PowerLawResistance", {"m_flow_small"}, fill("",0), true);
convertModifiers("IBPSA.Airflow.Multizone.BaseClasses.TwoWayFlowElement", {"m1_flow_small", "m2_flow_small"}, fill("",0), true);
convertModifiers("IBPSA.Airflow.Multizone.EffectiveAirLeakageArea", {"m_flow_small"}, fill("",0), true);
convertModifiers("IBPSA.Airflow.Multizone.Orifice", {"m_flow_small"}, fill("",0), true);
convertModifiers("IBPSA.Airflow.Multizone.DoorDiscretizedOpen", {"m1_flow_small", "m2_flow_small"}, fill("",0), true);
convertModifiers("IBPSA.Airflow.Multizone.DoorDiscretizedOperable", {"m1_flow_small", "m2_flow_small"}, fill("",0), true);
convertModifiers("IBPSA.Airflow.Multizone.ZonalFlow_ACS", …
```
> Set m_flow_small to final

- IBPSA/BoundaryConditions/WeatherData/BaseClasses/PartialLimiter.mo
> added missing right bracket, #1420

- IBPSA/Fluid/HeatExchangers/BaseClasses/PartialEffectivenessNTU.mo
Originally this change was only to fix the calculation in the error message, but looking further into it, I also figured that the `abs` is redundant in the calculation of `eps_nominal`.
Reasoning: Without the `abs`, you could rewrite the `eps_nominal` equation like so:
```
eps_nominal = (T_b2_nominal - T_a2_nominal) / (T_a1_nominal - T_a2_nominal)
```
The factor `(T_b2_nominal - T_a2_nominal) / (T_a1_nominal - T_a2_nominal)` is always positive when the user selected nominal values are right: side 2 is heating up (b2 >= a2) if and only if side 1 comes in hotter (a1 >= a2). If the values are wrong, then the following `assert` statement would catch it (`eps_nominal < 0`).
> Better error message for out of bound eps

- IBPSA/Resources/C-Sources/cryptographicsHash.c
- IBPSA/Resources/C-Sources/getTimeSpan.c
- IBPSA/Resources/C-Sources/getTimeSpan.h
Particularly, avoid the resource leak of the allocated string.
This integrates https://github.com/ibpsa/modelica-ibpsa/pull/1457
> Utilize Modelica compliant string allocation

- IBPSA/Media/Air.mo
This PR contains the changes from https://github.com/ibpsa/modelica-ibpsa/pull/1515
It makes the `BaseProperties` in `Media.Air` replaceable so that they can be change for compatibility with `Modelica.Media.Air.MoistAir`. 
Making `IBPSA.Media.Air` compatible would require introducing a call to `p_steam_sat = min(saturationPressure(T), 0.999*p);` which is an expensive function in the `BaseProperties`. Also, it would introduce `p_steam_sat`, which may be confusing to users because we don't model the amount of steam vs condensed water.
> Make BaseProperties replaceable in Media.Air

- IBPSA/Media/Air.mo
This will enable the Air model to be extended by instantiating models for such purposes as providing compatibility with Modelica.Media.Air.MoistAir.
> Make Media.Air BaseProperties replaceable

- IBPSA/Resources/C-Sources/cryptographicsHash.c
This integrates https://github.com/lbl-srg/modelica-buildings/pull/2784
It avoids a wrong memory access in OpenModelica
> Included ModelicaAllocateString.h in cryptographicsHash.c

- IBPSA/Fluid/Movers/SpeedControlled_Nrpm.mo
> changed rotational speed unit

- IBPSA/Fluid/Interfaces/PartialEightPortInterface.mo
This corrects the name of a port. The old implementation used a port name that does not exist.
> Corrected wrong port name

- IBPSA/Utilities/IO/SignalExchange/Overwrite.mo
- IBPSA/Utilities/IO/SignalExchange/Read.mo
This is for https://github.com/ibpsa/modelica-ibpsa/issues/1585.  Namely, it makes the parameters ``IBPSA.Utilities.IO.SignalExchange.Read.boptestRead`` and ``IBPSA.Utilities.IO.SignalExchange.Overwrite.boptestOverwrite`` unprotected.
@kbenne this should solve your problem with compiling BOPTEST test case using Spawn.
> Issue1585 protected se block

- IBPSA/Resources/C-Sources/jsonWriterInit.c
This is required because the C code calls ModelicaFormatError which is defined in the missing header file
> Added missing header file inclusion

- IBPSA/Utilities/Math/Functions/BaseClasses/der_spliceFunction.mo
- IBPSA/Utilities/Math/Functions/spliceFunction.mo
this is a follow-up for #1531 and #1532
there are two if-conditions that used a different value: 1 versus 0.9999999999
this PR makes sure the identical limit is used in
spliceFunction and corresponding derivative
This integrates https://github.com/ibpsa/modelica-ibpsa/pull/1640
> der_spliceFunction check limits

- IBPSA/Media/Examples/BaseClasses/TestTemperatureEnthalpyInversion.mo
This closes #1657.
It reformulates the if-expression to avoid a state event
> Avoided state event where time event can be generated

- IBPSA/Fluid/Actuators/BaseClasses/PartialThreeWayValve.mo
> Assigned parameter riseTime in valve instances

- IBPSA/Fluid/Sensors/BaseClasses/PartialDynamicFlowSensor.mo
This closes #1671.
It avoids comparing a real-valued parameter for equality which is not permitted by the Modelica Language Standard
> Corrected annotation

- IBPSA/BoundaryConditions/SolarIrradiation/BaseClasses/SkyClearness.mo
This pull request is for #1713 to fix variable typo `HGloHor` to `HDirNor` in documentation.
> Updated SkyClearness documentation

- IBPSA/Fluid/HeatExchangers/BaseClasses/PartialEffectiveness.mo
It turns out that the assignment of the `nominal` attribute leads in Dymola to a warning about non-literal nominal values. This addition to the previous pull requests moves parameter assignment from the `initial equation` section to the parameter declaration which avoids this warning.
> Moved assignments to paramater declaration

- IBPSA/Resources/C-Sources/jsonWriterInit.c
This corrects a pointer that was wrong in the PR for #1751
See https://github.com/lbl-srg/modelica-buildings/issues/3382#issuecomment-1546721932
> Corrected pointer

- IBPSA/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/BaseClasses/Functions/convectionResistanceCircularPipe.mo
- IBPSA/Fluid/Geothermal/Borefields/BaseClasses/Boreholes/BaseClasses/Functions/partialInternalResistances.mo
For #1762.
This corrects the variability as assigning an input to a parameter is not allowed
> Corrected variability in borehole function

- IBPSA/Electrical/AC/ThreePhasesUnbalanced/Lines/TwoPortRL.mo
- IBPSA/Electrical/Interfaces/PartialTwoPort.mo
This closes #1772.
It adds the constraining type which is needed, otherwise Optimica issues a warning.
> Issue1772 electrical constraining class

- IBPSA/Fluid/Interfaces/PartialFourPort.mo
- IBPSA/Fluid/Interfaces/PartialTwoPort.mo
- IBPSA/Fluid/Interfaces/PartialTwoPortVector.mo
- IBPSA/Fluid/Storage/BaseClasses/PartialStratified.mo
- IBPSA/Fluid/Storage/Examples/Stratified.mo
- IBPSA/Fluid/Storage/Examples/StratifiedEnhancedInternalHex.mo
- IBPSA/Fluid/Storage/Examples/StratifiedUnloadAtMinimumTemperature.mo
- IBPSA/Fluid/Storage/Stratified.mo
- IBPSA/Fluid/Storage/Validation/HeatExchangerDynamics.mo
This closes #1781.
I also proposed in commit 60c19a778 to modify port placement in `Fluid/Storage/BaseClasses/PartialStratified.mo`. Although it may annoy a few users (whose model diagrams will be modified) it will benefit many future users (with a more intuitive icon layout). But I can also revert that change if the disturbance is too big.
> Issue1781 port placement

- IBPSA/Media/Steam.mo
@mwetter: This is for Issue #1793. The first commit [a31c2be](https://github.com/ibpsa/modelica-ibpsa/commit/a31c2beac42230d1e9be5b7b4c8207a3d32ddc15) copies the changes made directly to `Buildings.Media.Steam` to `IBPSA.Media.Steam`. The next two commits add documentation (and fix typos previously missed), which are new to both repositories. 
Please let me know if you have any questions or if you need anything else. 
Thanks,
Katy
> Issue1793 steam documentation

- IBPSA/Examples/package.mo
This adds more information to the top-level documentation of IBPSA.Examples.
The changes have been made so we can automatically merge IBPSA to Buildings without overriding the documentation that Buildings had, and which was not added when we integrated the `Tutorial` into the IBPSA library.
> Updated documentation of Examples package

- IBPSA/ThermalZones/ISO13790/Zone5R1C/ZoneHVAC.mo
I added an annotation in `IBPSA.ThermalZones.ISO13790.Zone5R1C.ZoneHVAC` to allow the selection of medium. In this case, only Moist Air is available.
> Added missing annotation for medium selection in ISO13790 zone model

- IBPSA/Resources/C-Sources/fileWriterFree.c
- IBPSA/Resources/C-Sources/fileWriterStructure.c
- IBPSA/Resources/C-Sources/jsonWriterInit.c
This closes #1818
@LauraMaier : This is similar to https://github.com/ibpsa/modelica-ibpsa/pull/1817
> Added header files and ifdef statements

- IBPSA/Fluid/HeatPumps/ModularReversible/BaseClasses/PartialModularRefrigerantCycle.mo
- IBPSA/Fluid/HeatPumps/ModularReversible/RefrigerantCycle/BaseClasses/PartialRefrigerantCycle.mo
- IBPSA/Fluid/HeatPumps/ModularReversible/RefrigerantCycle/BaseClasses/PartialTableData2D.mo
- IBPSA/Fluid/HeatPumps/ModularReversible/Validation/BaseClasses/PartialValidation.mo
They have been removed as no other model sets `kW`. In Dymola and IMPACT, users could change all `W` to `kW` if they want to, in which case the setting is applied to all quantities with `W`, not just the ones declared here.
@FWuellhorst : If you agree please merge it to the development branch.
> Removed all 'kW' declarations

- IBPSA/Fluid/Movers/Data/Generic.mo
- IBPSA/Fluid/Movers/FlowControlled_dp.mo
- IBPSA/Obsolete/Fluid/Movers/Data/Generic.mo
> Corrected the use of displayUnit

- IBPSA/Fluid/FMI/Conversion/AirToOutlet.mo
- IBPSA/Fluid/FMI/Conversion/InletToAir.mo
This corrects a typo in the visible annotation that causes a warning in Dymola when saving the file
> Corrected typo in annotation

- IBPSA/Fluid/FMI/Conversion/AirToOutlet.mo
- IBPSA/Fluid/FMI/Conversion/InletToAir.mo
> Added causality to FMI conversion blocks

- IBPSA/Utilities/Time/CalendarTime.mo
- IBPSA/Utilities/Time/Types/ZeroTime.mo
Allow reference years later than 2020 and extend functionality to the year 2050.
> Issue1847 extend functionality CalendarTime

- IBPSA/Fluid/FMI/Adaptors/Inlet.mo
- IBPSA/Fluid/FMI/Adaptors/Outlet.mo
- IBPSA/Fluid/FMI/FlowSplitter_u.mo
- IBPSA/Fluid/FMI/Sink_T.mo
- IBPSA/Fluid/FMI/Source_T.mo
- IBPSA/Resources/ReferenceResults/Dymola/IBPSA_Fluid_FMI_ExportContainers_Examples_FMUs_FlowSplitter_u.txt
This closes #1853
This adds more missing `input` and `output` prefixes, similarly to https://github.com/ibpsa/modelica-ibpsa/pull/1835
> Added missing causality

- IBPSA/Airflow/Multizone/Examples/CO2TransportStep.mo
- IBPSA/Fluid/Sensors/Conversions/Examples/To_VolumeFraction.mo
- IBPSA/Fluid/Sources/Examples/TraceSubstancesFlowSource.mo
- IBPSA/ThermalZones/ReducedOrder/Validation/RoomWithLatentGain.mo
- IBPSA/ThermalZones/ReducedOrder/Validation/RoomWithoutLatentGain.mo
This configures the sensor so that no warning is issued due to one port connection, as this type of connection is fine for these examples.
This closes #1857
> Changed sensor configuration to avoid warning

- IBPSA/Resources/C-Sources/WeeklySchedule.c
- IBPSA/Resources/C-Sources/WeeklySchedule.h
- IBPSA/Resources/Data/schedule.txt
- IBPSA/Resources/Data/scheduleWindows.txt
- IBPSA/Utilities/IO/Files/Examples/WeeklySchedule.mo
> removed weekly schedule header impelementation for #1869

- IBPSA/Fluid/FMI/ExportContainers/Examples/FMUs/Fan.mo
- IBPSA/Fluid/FMI/ExportContainers/Examples/FMUs/HVACZones.mo
- IBPSA/Fluid/Geothermal/Borefields/Examples/RectangularBorefield.mo
- IBPSA/Fluid/Movers/Data/Generic.mo
- IBPSA/Fluid/Movers/Examples/MoverParameter.mo
- IBPSA/Fluid/Movers/Validation/FlowControlled_dp.mo
- IBPSA/Fluid/Movers/Validation/FlowControlled_dpSystem.mo
- IBPSA/Fluid/Movers/Validation/FlowControlled_m_flow.mo
- IBPSA/Fluid/Movers/Validation/PumpCurveDerivatives.mo
- IBPSA/Fluid/Movers/Validation/Pump_y_stratos.mo
This closes #1878.
This PR merges changes made in https://github.com/lbl-srg/modelica-buildings/pull/3830 that are applicable to IBPSA.
> Models in the `Obsolete` package are skipped.
> The following models are also skipped because they are planned to be obsoleted in a separate issue: `Fluid.Movers.Validation.{PowerEuler,PowerExact,PowerSimplified}`.
> issue1878 mover model warnings

- IBPSA/ThermalZones/ISO13790/Validation/BESTEST/Case900.mo
- IBPSA/ThermalZones/ISO13790/Validation/BESTEST/Data/Case600Results.mo
- IBPSA/ThermalZones/ISO13790/Zone5R1C/Zone.mo
> Issue1874 connector to itself and floating point representation

- IBPSA/Fluid/Geothermal/Borefields/UsersGuide.mo
This updates the documentation for the borefield models.
The change is mainly to remove the "currently" as it implies that changes will be done to the model.
> Update documentation for borefield models

- IBPSA/Fluid/Delays/DelayFirstOrder.mo
> Moved parameter tau to main tab

- IBPSA/Fluid/HeatPumps/ModularReversible/BaseClasses/PartialReversibleRefrigerantMachine.mo
This is to allow use of the refactored BuildingsPy, see https://github.com/lbl-srg/BuildingsPy/issues/566
that properly adds/removes code for AixLib. Other libraries worked already, and won't change the behavior due to this PR.
This closes #1919
> Changed markup commands in heat pump base class

- IBPSA/Fluid/Interfaces/EightPort.mo
- IBPSA/Fluid/Interfaces/PartialFourPort.mo
> Issue1924 dropdown medium choices

- .github/workflows/formatting.yml
- .travis.yml
- IBPSA/Resources/Scripts/BuildingsPy/conf.yml
- bin/runUnitTests.py
This closes #1939
This commit also increases BuildingsPy to 5.1.0 and adds the code to regenerate the configuration file, which was added in v5.1.0
> Updated OMC to 1.24.0

- IBPSA/Electrical/DC/Loads/Resistor.mo
This is to port the improvement for Buildings, #4032
> Changed guard against division by zero in electrical resistance

- IBPSA/Fluid/Sources/Examples/Outside_CpLowRise.mo
This simply corrects a hyperlink to an issue on the Buildings github page.
> Corrected hyperlink in Outside_CpLowRise.mo

- IBPSA/Fluid/MixingVolumes/Validation/MixingVolume.mo
> Changed tolerance of assertion block

- IBPSA/Fluid/Chillers/ModularReversible/RefrigerantCycle/ConstantCarnotEffectiveness.mo
- IBPSA/Fluid/HeatPumps/ModularReversible/BaseClasses/PartialReversibleRefrigerantMachine.mo
- IBPSA/Fluid/HeatPumps/ModularReversible/RefrigerantCycle/BaseClasses/PartialCarnot.mo
- IBPSA/Fluid/HeatPumps/ModularReversible/RefrigerantCycle/BaseClasses/PartialHeatPumpCycle.mo
- IBPSA/Fluid/HeatPumps/ModularReversible/RefrigerantCycle/BaseClasses/PartialTableData2D.mo
- IBPSA/Fluid/HeatPumps/ModularReversible/RefrigerantCycle/ConstantCarnotEffectiveness.mo
This closes #1927 and fixes a typo in the `iceFac` of the heating operation of a heat pump. I opted against moving the `RefrigerantCycleInertia` into the Dynamics tab as it may not only be used for dynamics (I model start-stop losses with this block) and is an important setting as the underlying data is steady state.
> Issue1927 ref cyc update

- IBPSA/BoundaryConditions/SolarIrradiation/BaseClasses/BrighteningCoefficient.mo
- IBPSA/Controls/SetPoints/OccupancySchedule.mo
- IBPSA/Electrical/PhaseSystems/ThreePhase_d.mo
- IBPSA/Electrical/PhaseSystems/package.mo
- IBPSA/Fluid/Actuators/Dampers/MixingBox.mo
- IBPSA/Fluid/BaseClasses/ActuatorFilter.mo
- IBPSA/Fluid/HeatExchangers/BaseClasses/PartialEffectivenessNTU.mo
- IBPSA/Fluid/HeatExchangers/BaseClasses/epsilon_ntuZ.mo
- IBPSA/Fluid/HeatExchangers/BaseClasses/ntu_epsilonZ.mo
- IBPSA/Fluid/HeatExchangers/WetCoilEffectivenessNTU.mo
- IBPSA/Fluid/Movers/BaseClasses/FlowMachineInterface.mo
- IBPSA/Fluid/Storage/BaseClasses/PartialStratified.mo
- IBPSA/ThermalZones/ReducedOrder/SolarGain/CorrectionGDoublePane.mo
> Remove import statements

- IBPSA/Controls/OBC/CDL/Logical/TrueFalseHold.mo
> Ported changes from Buildings for CDL.Logica.TrueFalseHold

- .github/workflows/formatting.yml
- .travis.yml
This updates the BuildingsPy version to the latest official release.
> Update BuildingsPy to 5.2.0

- IBPSA/Fluid/HeatPumps/ModularReversible/UsersGuide.mo
> Add description of new models from MBL

- IBPSA/Resources/Scripts/Conversion/ConvertIBPSA_from_3.0_to_4.0.mos
> Fix conversion script #2019
